//// ActionList unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/action_list
import m3e/list_variant

pub fn action_list_render_test() {
  let mod = action_list.new(list_variant.Standard)
  let mod_variant = action_list.new(list_variant.Segmented)

  let cases = [
    #(#(mod, [], []), element.element("m3e-action-list", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-action-list", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-action-list", [], [html.br([])]),
    ),

    #(
      #(mod_variant, [], []),
      element.element(
        "m3e-action-list",
        [
          attribute.attribute(
            "variant",
            list_variant.to_string(list_variant.Segmented),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    action_list.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
