//// BottomSheetTrigger unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/bottom_sheet_trigger.{Config}

pub fn bottom_sheet_trigger_default_config_test() {
  let cases = [
    Config(
      detent: None,
      secondary: bottom_sheet_trigger.IsNotSecondary,
      for: None,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    bottom_sheet_trigger.default_config()
    |> should.equal(expected)
  })
}

pub fn bottom_sheet_trigger_from_config_test() {
  let cases = [
    #(
      bottom_sheet_trigger.Config(
        detent: Some(42.0),
        secondary: bottom_sheet_trigger.IsSecondary,
        for: Some("test"),
      ),
      bottom_sheet_trigger.new()
        |> bottom_sheet_trigger.detent(Some(42.0))
        |> bottom_sheet_trigger.secondary(bottom_sheet_trigger.IsSecondary)
        |> bottom_sheet_trigger.for(Some("test")),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    bottom_sheet_trigger.from_config(config)
    |> should.equal(expected)
  })
}

pub fn bottom_sheet_trigger_new_test() {
  let cases = [
    bottom_sheet_trigger.from_config(bottom_sheet_trigger.Config(
      detent: None,
      secondary: bottom_sheet_trigger.IsNotSecondary,
      for: None,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    bottom_sheet_trigger.new()
    |> should.equal(expected)
  })
}

pub fn bottom_sheet_trigger_detent_test() {
  let mod = bottom_sheet_trigger.new()
  let cases = [
    #(
      Some(42.0),
      bottom_sheet_trigger.from_config(
        bottom_sheet_trigger.Config(
          ..bottom_sheet_trigger.default_config(),
          detent: Some(42.0),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    bottom_sheet_trigger.detent(mod, field)
    |> should.equal(expected)
  })
}

pub fn bottom_sheet_trigger_secondary_test() {
  let mod = bottom_sheet_trigger.new()
  let cases = [
    #(
      bottom_sheet_trigger.IsSecondary,
      bottom_sheet_trigger.from_config(
        bottom_sheet_trigger.Config(
          ..bottom_sheet_trigger.default_config(),
          secondary: bottom_sheet_trigger.IsSecondary,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    bottom_sheet_trigger.secondary(mod, field)
    |> should.equal(expected)
  })
}

pub fn bottom_sheet_trigger_for_test() {
  let mod = bottom_sheet_trigger.new()
  let cases = [
    #(
      Some("test"),
      bottom_sheet_trigger.from_config(
        bottom_sheet_trigger.Config(
          ..bottom_sheet_trigger.default_config(),
          for: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    bottom_sheet_trigger.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn bottom_sheet_trigger_render_test() {
  let mod = bottom_sheet_trigger.new()

  let mod_detent =
    bottom_sheet_trigger.new() |> bottom_sheet_trigger.detent(Some(42.0))
  let mod_secondary =
    bottom_sheet_trigger.new()
    |> bottom_sheet_trigger.secondary(bottom_sheet_trigger.IsSecondary)
  let mod_for =
    bottom_sheet_trigger.new() |> bottom_sheet_trigger.for(Some("test"))

  let cases = [
    #(#(mod, [], []), element.element("m3e-bottom-sheet-trigger", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-bottom-sheet-trigger", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-bottom-sheet-trigger", [], [html.br([])]),
    ),

    #(
      #(mod_detent, [], []),
      element.element(
        "m3e-bottom-sheet-trigger",
        [attribute.attribute("detent", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_secondary, [], []),
      element.element(
        "m3e-bottom-sheet-trigger",
        [attribute.attribute("secondary", "")],
        [],
      ),
    ),
    #(
      #(mod_for, [], []),
      element.element(
        "m3e-bottom-sheet-trigger",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    bottom_sheet_trigger.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
