//// Calendar unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/calendar.{Config}
import m3e/calendar_view
import m3e/date

pub fn calendar_default_config_test() {
  let cases = [
    Config(
      date: None,
      max_date: None,
      min_date: None,
      range_end: None,
      range_start: None,
      start_at: None,
      start_view: calendar_view.Month,
      previous_month_label: "Previous month",
      next_month_label: "Next month",
      previous_year_label: "Previous year",
      next_year_label: "Next year",
      previous_multi_year_label: "Previous 24 years",
      next_multi_year_label: "Next 24 years",
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    calendar.default_config()
    |> should.equal(expected)
  })
}

pub fn calendar_from_config_test() {
  let cases = [
    #(
      calendar.Config(
        date: Some(date.today_utc()),
        max_date: Some(date.today_utc()),
        min_date: Some(date.today_utc()),
        range_end: Some(date.today_utc()),
        range_start: Some(date.today_utc()),
        start_at: Some(date.today_utc()),
        start_view: calendar_view.Year,
        previous_month_label: "test",
        next_month_label: "test",
        previous_year_label: "test",
        next_year_label: "test",
        previous_multi_year_label: "test",
        next_multi_year_label: "test",
      ),
      calendar.new()
        |> calendar.date(Some(date.today_utc()))
        |> calendar.max_date(Some(date.today_utc()))
        |> calendar.min_date(Some(date.today_utc()))
        |> calendar.range_end(Some(date.today_utc()))
        |> calendar.range_start(Some(date.today_utc()))
        |> calendar.start_at(Some(date.today_utc()))
        |> calendar.start_view(calendar_view.Year)
        |> calendar.previous_month_label("test")
        |> calendar.next_month_label("test")
        |> calendar.previous_year_label("test")
        |> calendar.next_year_label("test")
        |> calendar.previous_multi_year_label("test")
        |> calendar.next_multi_year_label("test"),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    calendar.from_config(config)
    |> should.equal(expected)
  })
}

pub fn calendar_new_test() {
  let cases = [
    calendar.from_config(calendar.Config(
      date: None,
      max_date: None,
      min_date: None,
      range_end: None,
      range_start: None,
      start_at: None,
      start_view: calendar_view.Month,
      previous_month_label: "Previous month",
      next_month_label: "Next month",
      previous_year_label: "Previous year",
      next_year_label: "Next year",
      previous_multi_year_label: "Previous 24 years",
      next_multi_year_label: "Next 24 years",
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    calendar.new()
    |> should.equal(expected)
  })
}

pub fn calendar_date_test() {
  let mod = calendar.new()
  let cases = [
    #(
      Some(date.today_utc()),
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          date: Some(date.today_utc()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.date(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_max_date_test() {
  let mod = calendar.new()
  let cases = [
    #(
      Some(date.today_utc()),
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          max_date: Some(date.today_utc()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.max_date(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_min_date_test() {
  let mod = calendar.new()
  let cases = [
    #(
      Some(date.today_utc()),
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          min_date: Some(date.today_utc()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.min_date(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_range_end_test() {
  let mod = calendar.new()
  let cases = [
    #(
      Some(date.today_utc()),
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          range_end: Some(date.today_utc()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.range_end(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_range_start_test() {
  let mod = calendar.new()
  let cases = [
    #(
      Some(date.today_utc()),
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          range_start: Some(date.today_utc()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.range_start(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_start_at_test() {
  let mod = calendar.new()
  let cases = [
    #(
      Some(date.today_utc()),
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          start_at: Some(date.today_utc()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.start_at(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_start_view_test() {
  let mod = calendar.new()
  let cases = [
    #(
      calendar_view.Year,
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          start_view: calendar_view.Year,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.start_view(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_previous_month_label_test() {
  let mod = calendar.new()
  let cases = [
    #(
      "test",
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          previous_month_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.previous_month_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_next_month_label_test() {
  let mod = calendar.new()
  let cases = [
    #(
      "test",
      calendar.from_config(
        calendar.Config(..calendar.default_config(), next_month_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.next_month_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_previous_year_label_test() {
  let mod = calendar.new()
  let cases = [
    #(
      "test",
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          previous_year_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.previous_year_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_next_year_label_test() {
  let mod = calendar.new()
  let cases = [
    #(
      "test",
      calendar.from_config(
        calendar.Config(..calendar.default_config(), next_year_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.next_year_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_previous_multi_year_label_test() {
  let mod = calendar.new()
  let cases = [
    #(
      "test",
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          previous_multi_year_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.previous_multi_year_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_next_multi_year_label_test() {
  let mod = calendar.new()
  let cases = [
    #(
      "test",
      calendar.from_config(
        calendar.Config(
          ..calendar.default_config(),
          next_multi_year_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    calendar.next_multi_year_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn calendar_render_test() {
  let mod = calendar.new()

  let mod_date = calendar.new() |> calendar.date(Some(date.today_utc()))
  let mod_max_date = calendar.new() |> calendar.max_date(Some(date.today_utc()))
  let mod_min_date = calendar.new() |> calendar.min_date(Some(date.today_utc()))
  let mod_range_end =
    calendar.new() |> calendar.range_end(Some(date.today_utc()))
  let mod_range_start =
    calendar.new() |> calendar.range_start(Some(date.today_utc()))
  let mod_start_at = calendar.new() |> calendar.start_at(Some(date.today_utc()))
  let mod_start_view = calendar.new() |> calendar.start_view(calendar_view.Year)
  let mod_previous_month_label =
    calendar.new() |> calendar.previous_month_label("test")
  let mod_next_month_label = calendar.new() |> calendar.next_month_label("test")
  let mod_previous_year_label =
    calendar.new() |> calendar.previous_year_label("test")
  let mod_next_year_label = calendar.new() |> calendar.next_year_label("test")
  let mod_previous_multi_year_label =
    calendar.new() |> calendar.previous_multi_year_label("test")
  let mod_next_multi_year_label =
    calendar.new() |> calendar.next_multi_year_label("test")

  let cases = [
    #(#(mod, [], []), element.element("m3e-calendar", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-calendar", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-calendar", [], [html.br([])]),
    ),

    #(
      #(mod_date, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("date", date.to_string(date.today_utc()))],
        [],
      ),
    ),
    #(
      #(mod_max_date, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("max-date", date.to_string(date.today_utc()))],
        [],
      ),
    ),
    #(
      #(mod_min_date, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("min-date", date.to_string(date.today_utc()))],
        [],
      ),
    ),
    #(
      #(mod_range_end, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("range-end", date.to_string(date.today_utc()))],
        [],
      ),
    ),
    #(
      #(mod_range_start, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("range-start", date.to_string(date.today_utc()))],
        [],
      ),
    ),
    #(
      #(mod_start_at, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("start-at", date.to_string(date.today_utc()))],
        [],
      ),
    ),
    #(
      #(mod_start_view, [], []),
      element.element(
        "m3e-calendar",
        [
          attribute.attribute(
            "start-view",
            calendar_view.to_string(calendar_view.Year),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_previous_month_label, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("previous-month-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_next_month_label, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("next-month-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_previous_year_label, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("previous-year-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_next_year_label, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("next-year-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_previous_multi_year_label, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("previous-multi-year-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_next_multi_year_label, [], []),
      element.element(
        "m3e-calendar",
        [attribute.attribute("next-multi-year-label", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    calendar.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn calendar_slot_test() {
  let cases = [
    #(calendar.Header, attribute.attribute("slot", "header")),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    calendar.slot(s)
    |> should.equal(expected)
  })
}
