//// Chip unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/chip.{Config}
import m3e/chip_variant

pub fn chip_default_config_test() {
  let cases = [
    Config(value: "", variant: chip_variant.Outlined),
  ]

  list.each(cases, fn(c) {
    let expected = c

    chip.default_config()
    |> should.equal(expected)
  })
}

pub fn chip_from_config_test() {
  let cases = [
    #(
      chip.Config(value: "test", variant: chip_variant.Elevated),
      chip.new()
        |> chip.value("test")
        |> chip.variant(chip_variant.Elevated),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    chip.from_config(config)
    |> should.equal(expected)
  })
}

pub fn chip_new_test() {
  let cases = [
    chip.from_config(chip.Config(value: "", variant: chip_variant.Outlined)),
  ]

  list.each(cases, fn(c) {
    let expected = c

    chip.new()
    |> should.equal(expected)
  })
}

pub fn chip_value_test() {
  let mod = chip.new()
  let cases = [
    #(
      "test",
      chip.from_config(chip.Config(..chip.default_config(), value: "test")),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    chip.value(mod, field)
    |> should.equal(expected)
  })
}

pub fn chip_variant_test() {
  let mod = chip.new()
  let cases = [
    #(
      chip_variant.Elevated,
      chip.from_config(
        chip.Config(..chip.default_config(), variant: chip_variant.Elevated),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    chip.variant(mod, field)
    |> should.equal(expected)
  })
}

pub fn chip_render_test() {
  let mod = chip.new()

  let mod_value = chip.new() |> chip.value("test")
  let mod_variant = chip.new() |> chip.variant(chip_variant.Elevated)

  let cases = [
    #(#(mod, [], []), element.element("m3e-chip", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-chip", [attribute.id("id")], []),
    ),
    #(#(mod, [], [html.br([])]), element.element("m3e-chip", [], [html.br([])])),

    #(
      #(mod_value, [], []),
      element.element("m3e-chip", [attribute.attribute("value", "test")], []),
    ),
    #(
      #(mod_variant, [], []),
      element.element(
        "m3e-chip",
        [
          attribute.attribute(
            "variant",
            chip_variant.to_string(chip_variant.Elevated),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    chip.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn chip_slot_test() {
  let cases = [
    #(chip.Icon, attribute.attribute("slot", "icon")),
    #(chip.TrailingIcon, attribute.attribute("slot", "trailing-icon")),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    chip.slot(s)
    |> should.equal(expected)
  })
}
