//// Collapsible unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/collapsible

pub fn collapsible_render_test() {
  let mod = collapsible.new(collapsible.IsNotOpen)
  let mod_open = collapsible.new(collapsible.IsOpen)

  let cases = [
    #(#(mod, [], []), element.element("m3e-collapsible", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-collapsible", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-collapsible", [], [html.br([])]),
    ),

    #(
      #(mod_open, [], []),
      element.element("m3e-collapsible", [attribute.attribute("open", "")], []),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    collapsible.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
