//// ContentPane unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/content_pane

pub fn content_pane_render_test() {
  let mod = content_pane.new()

  let cases = [
    #(#(mod, [], []), element.element("m3e-content-pane", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-content-pane", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-content-pane", [], [html.br([])]),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    content_pane.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
