//// DialogAction unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/dialog_action

pub fn dialog_action_render_test() {
  let mod = dialog_action.new("")
  let mod_return_value = dialog_action.new("test")

  let cases = [
    #(#(mod, [], []), element.element("m3e-dialog-action", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-dialog-action", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-dialog-action", [], [html.br([])]),
    ),

    #(
      #(mod_return_value, [], []),
      element.element(
        "m3e-dialog-action",
        [attribute.attribute("return-value", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    dialog_action.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
