//// DrawerToggle unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/drawer_toggle

pub fn drawer_toggle_render_test() {
  let mod = drawer_toggle.new(None)
  let mod_for = drawer_toggle.new(Some("test"))

  let cases = [
    #(#(mod, []), element.element("m3e-drawer-toggle", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-drawer-toggle", [attribute.id("id")], []),
    ),

    #(
      #(mod_for, []),
      element.element(
        "m3e-drawer-toggle",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    drawer_toggle.render(mod, attributes)
    |> should.equal(expected)
  })
}
