//// FabMenuItem unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/fab_menu_item.{Config}
import m3e/link_target

pub fn fab_menu_item_default_config_test() {
  let cases = [
    Config(
      disabled: fab_menu_item.IsNotDisabled,
      download: None,
      href: "",
      rel: "",
      target: None,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    fab_menu_item.default_config()
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_from_config_test() {
  let cases = [
    #(
      fab_menu_item.Config(
        disabled: fab_menu_item.IsDisabled,
        download: Some("test"),
        href: "test",
        rel: "test",
        target: Some(link_target.Self),
      ),
      fab_menu_item.new()
        |> fab_menu_item.disabled(fab_menu_item.IsDisabled)
        |> fab_menu_item.download(Some("test"))
        |> fab_menu_item.href("test")
        |> fab_menu_item.rel("test")
        |> fab_menu_item.target(Some(link_target.Self)),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    fab_menu_item.from_config(config)
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_new_test() {
  let cases = [
    fab_menu_item.from_config(fab_menu_item.Config(
      disabled: fab_menu_item.IsNotDisabled,
      download: None,
      href: "",
      rel: "",
      target: None,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    fab_menu_item.new()
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_disabled_test() {
  let mod = fab_menu_item.new()
  let cases = [
    #(
      fab_menu_item.IsDisabled,
      fab_menu_item.from_config(
        fab_menu_item.Config(
          ..fab_menu_item.default_config(),
          disabled: fab_menu_item.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fab_menu_item.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_download_test() {
  let mod = fab_menu_item.new()
  let cases = [
    #(
      Some("test"),
      fab_menu_item.from_config(
        fab_menu_item.Config(
          ..fab_menu_item.default_config(),
          download: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fab_menu_item.download(mod, field)
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_href_test() {
  let mod = fab_menu_item.new()
  let cases = [
    #(
      "test",
      fab_menu_item.from_config(
        fab_menu_item.Config(..fab_menu_item.default_config(), href: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fab_menu_item.href(mod, field)
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_rel_test() {
  let mod = fab_menu_item.new()
  let cases = [
    #(
      "test",
      fab_menu_item.from_config(
        fab_menu_item.Config(..fab_menu_item.default_config(), rel: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fab_menu_item.rel(mod, field)
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_target_test() {
  let mod = fab_menu_item.new()
  let cases = [
    #(
      Some(link_target.Self),
      fab_menu_item.from_config(
        fab_menu_item.Config(
          ..fab_menu_item.default_config(),
          target: Some(link_target.Self),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fab_menu_item.target(mod, field)
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_render_test() {
  let mod = fab_menu_item.new()

  let mod_disabled =
    fab_menu_item.new() |> fab_menu_item.disabled(fab_menu_item.IsDisabled)
  let mod_download = fab_menu_item.new() |> fab_menu_item.download(Some("test"))
  let mod_href = fab_menu_item.new() |> fab_menu_item.href("test")
  let mod_rel = fab_menu_item.new() |> fab_menu_item.rel("test")
  let mod_target =
    fab_menu_item.new() |> fab_menu_item.target(Some(link_target.Self))

  let cases = [
    #(#(mod, [], []), element.element("m3e-fab-menu-item", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-fab-menu-item", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-fab-menu-item", [], [html.br([])]),
    ),

    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-fab-menu-item",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_download, [], []),
      element.element(
        "m3e-fab-menu-item",
        [attribute.attribute("download", "test")],
        [],
      ),
    ),
    #(
      #(mod_href, [], []),
      element.element(
        "m3e-fab-menu-item",
        [attribute.attribute("href", "test")],
        [],
      ),
    ),
    #(
      #(mod_rel, [], []),
      element.element(
        "m3e-fab-menu-item",
        [attribute.attribute("rel", "test")],
        [],
      ),
    ),
    #(
      #(mod_target, [], []),
      element.element(
        "m3e-fab-menu-item",
        [attribute.attribute("target", link_target.to_string(link_target.Self))],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    fab_menu_item.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn fab_menu_item_slot_test() {
  let cases = [
    #(fab_menu_item.Icon, attribute.attribute("slot", "icon")),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    fab_menu_item.slot(s)
    |> should.equal(expected)
  })
}
