//// FabMenu unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/fab_menu
import m3e/fab_menu_variant

pub fn fab_menu_render_test() {
  let mod = fab_menu.new(fab_menu_variant.Primary)
  let mod_variant = fab_menu.new(fab_menu_variant.Secondary)

  let cases = [
    #(#(mod, [], []), element.element("m3e-fab-menu", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-fab-menu", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-fab-menu", [], [html.br([])]),
    ),

    #(
      #(mod_variant, [], []),
      element.element(
        "m3e-fab-menu",
        [
          attribute.attribute(
            "variant",
            fab_menu_variant.to_string(fab_menu_variant.Secondary),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    fab_menu.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
