//// FilterChip unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/chip_variant
import m3e/filter_chip.{Config}

pub fn filter_chip_default_config_test() {
  let cases = [
    Config(
      disabled: filter_chip.IsNotDisabled,
      disabled_interactive: filter_chip.IsNotDisabledInteractive,
      selected: filter_chip.IsNotSelected,
      value: "",
      variant: chip_variant.Outlined,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    filter_chip.default_config()
    |> should.equal(expected)
  })
}

pub fn filter_chip_from_config_test() {
  let cases = [
    #(
      filter_chip.Config(
        disabled: filter_chip.IsDisabled,
        disabled_interactive: filter_chip.IsDisabledInteractive,
        selected: filter_chip.IsSelected,
        value: "test",
        variant: chip_variant.Elevated,
      ),
      filter_chip.new()
        |> filter_chip.disabled(filter_chip.IsDisabled)
        |> filter_chip.disabled_interactive(filter_chip.IsDisabledInteractive)
        |> filter_chip.selected(filter_chip.IsSelected)
        |> filter_chip.value("test")
        |> filter_chip.variant(chip_variant.Elevated),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    filter_chip.from_config(config)
    |> should.equal(expected)
  })
}

pub fn filter_chip_new_test() {
  let cases = [
    filter_chip.from_config(filter_chip.Config(
      disabled: filter_chip.IsNotDisabled,
      disabled_interactive: filter_chip.IsNotDisabledInteractive,
      selected: filter_chip.IsNotSelected,
      value: "",
      variant: chip_variant.Outlined,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    filter_chip.new()
    |> should.equal(expected)
  })
}

pub fn filter_chip_disabled_test() {
  let mod = filter_chip.new()
  let cases = [
    #(
      filter_chip.IsDisabled,
      filter_chip.from_config(
        filter_chip.Config(
          ..filter_chip.default_config(),
          disabled: filter_chip.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_disabled_interactive_test() {
  let mod = filter_chip.new()
  let cases = [
    #(
      filter_chip.IsDisabledInteractive,
      filter_chip.from_config(
        filter_chip.Config(
          ..filter_chip.default_config(),
          disabled_interactive: filter_chip.IsDisabledInteractive,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip.disabled_interactive(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_selected_test() {
  let mod = filter_chip.new()
  let cases = [
    #(
      filter_chip.IsSelected,
      filter_chip.from_config(
        filter_chip.Config(
          ..filter_chip.default_config(),
          selected: filter_chip.IsSelected,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip.selected(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_value_test() {
  let mod = filter_chip.new()
  let cases = [
    #(
      "test",
      filter_chip.from_config(
        filter_chip.Config(..filter_chip.default_config(), value: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip.value(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_variant_test() {
  let mod = filter_chip.new()
  let cases = [
    #(
      chip_variant.Elevated,
      filter_chip.from_config(
        filter_chip.Config(
          ..filter_chip.default_config(),
          variant: chip_variant.Elevated,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip.variant(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_render_test() {
  let mod = filter_chip.new()

  let mod_disabled =
    filter_chip.new() |> filter_chip.disabled(filter_chip.IsDisabled)
  let mod_disabled_interactive =
    filter_chip.new()
    |> filter_chip.disabled_interactive(filter_chip.IsDisabledInteractive)
  let mod_selected =
    filter_chip.new() |> filter_chip.selected(filter_chip.IsSelected)
  let mod_value = filter_chip.new() |> filter_chip.value("test")
  let mod_variant =
    filter_chip.new() |> filter_chip.variant(chip_variant.Elevated)

  let cases = [
    #(#(mod, [], []), element.element("m3e-filter-chip", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-filter-chip", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-filter-chip", [], [html.br([])]),
    ),

    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-filter-chip",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_disabled_interactive, [], []),
      element.element(
        "m3e-filter-chip",
        [attribute.attribute("disabled-interactive", "")],
        [],
      ),
    ),
    #(
      #(mod_selected, [], []),
      element.element(
        "m3e-filter-chip",
        [attribute.attribute("selected", "")],
        [],
      ),
    ),
    #(
      #(mod_value, [], []),
      element.element(
        "m3e-filter-chip",
        [attribute.attribute("value", "test")],
        [],
      ),
    ),
    #(
      #(mod_variant, [], []),
      element.element(
        "m3e-filter-chip",
        [
          attribute.attribute(
            "variant",
            chip_variant.to_string(chip_variant.Elevated),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    filter_chip.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn filter_chip_slot_test() {
  let cases = [
    #(filter_chip.Icon, attribute.attribute("slot", "icon")),
    #(filter_chip.TrailingIcon, attribute.attribute("slot", "trailing-icon")),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    filter_chip.slot(s)
    |> should.equal(expected)
  })
}
