//// FilterChipSet unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/filter_chip_set.{Config}

pub fn filter_chip_set_default_config_test() {
  let cases = [
    Config(
      disabled: filter_chip_set.IsNotDisabled,
      hide_selection_indicator: filter_chip_set.IsNotHideSelectionIndicator,
      multi: filter_chip_set.IsNotMulti,
      name: "",
      vertical: filter_chip_set.IsNotVertical,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    filter_chip_set.default_config()
    |> should.equal(expected)
  })
}

pub fn filter_chip_set_from_config_test() {
  let cases = [
    #(
      filter_chip_set.Config(
        disabled: filter_chip_set.IsDisabled,
        hide_selection_indicator: filter_chip_set.IsHideSelectionIndicator,
        multi: filter_chip_set.IsMulti,
        name: "test",
        vertical: filter_chip_set.IsVertical,
      ),
      filter_chip_set.new()
        |> filter_chip_set.disabled(filter_chip_set.IsDisabled)
        |> filter_chip_set.hide_selection_indicator(
          filter_chip_set.IsHideSelectionIndicator,
        )
        |> filter_chip_set.multi(filter_chip_set.IsMulti)
        |> filter_chip_set.name("test")
        |> filter_chip_set.vertical(filter_chip_set.IsVertical),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    filter_chip_set.from_config(config)
    |> should.equal(expected)
  })
}

pub fn filter_chip_set_new_test() {
  let cases = [
    filter_chip_set.from_config(filter_chip_set.Config(
      disabled: filter_chip_set.IsNotDisabled,
      hide_selection_indicator: filter_chip_set.IsNotHideSelectionIndicator,
      multi: filter_chip_set.IsNotMulti,
      name: "",
      vertical: filter_chip_set.IsNotVertical,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    filter_chip_set.new()
    |> should.equal(expected)
  })
}

pub fn filter_chip_set_disabled_test() {
  let mod = filter_chip_set.new()
  let cases = [
    #(
      filter_chip_set.IsDisabled,
      filter_chip_set.from_config(
        filter_chip_set.Config(
          ..filter_chip_set.default_config(),
          disabled: filter_chip_set.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip_set.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_set_hide_selection_indicator_test() {
  let mod = filter_chip_set.new()
  let cases = [
    #(
      filter_chip_set.IsHideSelectionIndicator,
      filter_chip_set.from_config(
        filter_chip_set.Config(
          ..filter_chip_set.default_config(),
          hide_selection_indicator: filter_chip_set.IsHideSelectionIndicator,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip_set.hide_selection_indicator(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_set_multi_test() {
  let mod = filter_chip_set.new()
  let cases = [
    #(
      filter_chip_set.IsMulti,
      filter_chip_set.from_config(
        filter_chip_set.Config(
          ..filter_chip_set.default_config(),
          multi: filter_chip_set.IsMulti,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip_set.multi(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_set_name_test() {
  let mod = filter_chip_set.new()
  let cases = [
    #(
      "test",
      filter_chip_set.from_config(
        filter_chip_set.Config(..filter_chip_set.default_config(), name: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip_set.name(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_set_vertical_test() {
  let mod = filter_chip_set.new()
  let cases = [
    #(
      filter_chip_set.IsVertical,
      filter_chip_set.from_config(
        filter_chip_set.Config(
          ..filter_chip_set.default_config(),
          vertical: filter_chip_set.IsVertical,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    filter_chip_set.vertical(mod, field)
    |> should.equal(expected)
  })
}

pub fn filter_chip_set_render_test() {
  let mod = filter_chip_set.new()

  let mod_disabled =
    filter_chip_set.new()
    |> filter_chip_set.disabled(filter_chip_set.IsDisabled)
  let mod_hide_selection_indicator =
    filter_chip_set.new()
    |> filter_chip_set.hide_selection_indicator(
      filter_chip_set.IsHideSelectionIndicator,
    )
  let mod_multi =
    filter_chip_set.new() |> filter_chip_set.multi(filter_chip_set.IsMulti)
  let mod_name = filter_chip_set.new() |> filter_chip_set.name("test")
  let mod_vertical =
    filter_chip_set.new()
    |> filter_chip_set.vertical(filter_chip_set.IsVertical)

  let cases = [
    #(#(mod, [], []), element.element("m3e-filter-chip-set", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-filter-chip-set", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-filter-chip-set", [], [html.br([])]),
    ),

    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-filter-chip-set",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_hide_selection_indicator, [], []),
      element.element(
        "m3e-filter-chip-set",
        [attribute.attribute("hide-selection-indicator", "")],
        [],
      ),
    ),
    #(
      #(mod_multi, [], []),
      element.element(
        "m3e-filter-chip-set",
        [attribute.attribute("multi", "")],
        [],
      ),
    ),
    #(
      #(mod_name, [], []),
      element.element(
        "m3e-filter-chip-set",
        [attribute.attribute("name", "test")],
        [],
      ),
    ),
    #(
      #(mod_vertical, [], []),
      element.element(
        "m3e-filter-chip-set",
        [attribute.attribute("vertical", "")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    filter_chip_set.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
