//// FlingGesture unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/fling_gesture.{Config}
import m3e/fling_gesture_direction
import m3e/gesture_input_button
import m3e/pointer_type

pub fn fling_gesture_default_config_test() {
  let cases = [
    Config(
      for: None,
      buttons: [gesture_input_button.Primary],
      pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
      disabled: fling_gesture.IsNotDisabled,
      priority: 1.0,
      min_displacement: 12.0,
      min_velocity: 0.3,
      direction_threshold: 12.0,
      directions: [
        fling_gesture_direction.Left,
        fling_gesture_direction.Right,
        fling_gesture_direction.Up,
        fling_gesture_direction.Down,
      ],
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    fling_gesture.default_config()
    |> should.equal(expected)
  })
}

pub fn fling_gesture_from_config_test() {
  let cases = [
    #(
      fling_gesture.Config(
        for: Some("test"),
        buttons: [gesture_input_button.Secondary],
        pointer_types: [pointer_type.Mouse],
        disabled: fling_gesture.IsDisabled,
        priority: 42.0,
        min_displacement: 42.0,
        min_velocity: 42.0,
        direction_threshold: 42.0,
        directions: [fling_gesture_direction.Left],
      ),
      fling_gesture.new()
        |> fling_gesture.for(Some("test"))
        |> fling_gesture.buttons([gesture_input_button.Secondary])
        |> fling_gesture.pointer_types([pointer_type.Mouse])
        |> fling_gesture.disabled(fling_gesture.IsDisabled)
        |> fling_gesture.priority(42.0)
        |> fling_gesture.min_displacement(42.0)
        |> fling_gesture.min_velocity(42.0)
        |> fling_gesture.direction_threshold(42.0)
        |> fling_gesture.directions([fling_gesture_direction.Left]),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    fling_gesture.from_config(config)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_new_test() {
  let cases = [
    fling_gesture.from_config(
      fling_gesture.Config(
        for: None,
        buttons: [gesture_input_button.Primary],
        pointer_types: [
          pointer_type.Mouse,
          pointer_type.Pen,
          pointer_type.Touch,
        ],
        disabled: fling_gesture.IsNotDisabled,
        priority: 1.0,
        min_displacement: 12.0,
        min_velocity: 0.3,
        direction_threshold: 12.0,
        directions: [
          fling_gesture_direction.Left,
          fling_gesture_direction.Right,
          fling_gesture_direction.Up,
          fling_gesture_direction.Down,
        ],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    fling_gesture.new()
    |> should.equal(expected)
  })
}

pub fn fling_gesture_for_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      Some("test"),
      fling_gesture.from_config(
        fling_gesture.Config(
          ..fling_gesture.default_config(),
          for: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_buttons_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      [gesture_input_button.Secondary],
      fling_gesture.from_config(
        fling_gesture.Config(..fling_gesture.default_config(), buttons: [
          gesture_input_button.Secondary,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.buttons(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_pointer_types_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      [pointer_type.Mouse],
      fling_gesture.from_config(
        fling_gesture.Config(..fling_gesture.default_config(), pointer_types: [
          pointer_type.Mouse,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.pointer_types(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_disabled_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      fling_gesture.IsDisabled,
      fling_gesture.from_config(
        fling_gesture.Config(
          ..fling_gesture.default_config(),
          disabled: fling_gesture.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_priority_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      42.0,
      fling_gesture.from_config(
        fling_gesture.Config(..fling_gesture.default_config(), priority: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.priority(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_min_displacement_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      42.0,
      fling_gesture.from_config(
        fling_gesture.Config(
          ..fling_gesture.default_config(),
          min_displacement: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.min_displacement(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_min_velocity_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      42.0,
      fling_gesture.from_config(
        fling_gesture.Config(
          ..fling_gesture.default_config(),
          min_velocity: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.min_velocity(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_direction_threshold_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      42.0,
      fling_gesture.from_config(
        fling_gesture.Config(
          ..fling_gesture.default_config(),
          direction_threshold: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.direction_threshold(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_directions_test() {
  let mod = fling_gesture.new()
  let cases = [
    #(
      [fling_gesture_direction.Left],
      fling_gesture.from_config(
        fling_gesture.Config(..fling_gesture.default_config(), directions: [
          fling_gesture_direction.Left,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    fling_gesture.directions(mod, field)
    |> should.equal(expected)
  })
}

pub fn fling_gesture_render_test() {
  let mod = fling_gesture.new()

  let mod_for = fling_gesture.new() |> fling_gesture.for(Some("test"))
  let mod_buttons =
    fling_gesture.new()
    |> fling_gesture.buttons([gesture_input_button.Secondary])
  let mod_pointer_types =
    fling_gesture.new() |> fling_gesture.pointer_types([pointer_type.Mouse])
  let mod_disabled =
    fling_gesture.new() |> fling_gesture.disabled(fling_gesture.IsDisabled)
  let mod_priority = fling_gesture.new() |> fling_gesture.priority(42.0)
  let mod_min_displacement =
    fling_gesture.new() |> fling_gesture.min_displacement(42.0)
  let mod_min_velocity = fling_gesture.new() |> fling_gesture.min_velocity(42.0)
  let mod_direction_threshold =
    fling_gesture.new() |> fling_gesture.direction_threshold(42.0)
  let mod_directions =
    fling_gesture.new()
    |> fling_gesture.directions([fling_gesture_direction.Left])
  let cases = [
    #(#(mod, []), element.element("m3e-fling-gesture", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-fling-gesture", [attribute.id("id")], []),
    ),

    #(
      #(mod_for, []),
      element.element(
        "m3e-fling-gesture",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
    #(
      #(mod_buttons, []),
      element.element(
        "m3e-fling-gesture",
        [
          attribute.attribute(
            "buttons",
            gesture_input_button.to_string(gesture_input_button.Secondary),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_pointer_types, []),
      element.element(
        "m3e-fling-gesture",
        [
          attribute.attribute(
            "pointer-types",
            pointer_type.to_string(pointer_type.Mouse),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_disabled, []),
      element.element(
        "m3e-fling-gesture",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_priority, []),
      element.element(
        "m3e-fling-gesture",
        [attribute.attribute("priority", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_min_displacement, []),
      element.element(
        "m3e-fling-gesture",
        [attribute.attribute("min-displacement", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_min_velocity, []),
      element.element(
        "m3e-fling-gesture",
        [attribute.attribute("min-velocity", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_direction_threshold, []),
      element.element(
        "m3e-fling-gesture",
        [attribute.attribute("direction-threshold", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_directions, []),
      element.element(
        "m3e-fling-gesture",
        [
          attribute.attribute(
            "directions",
            fling_gesture_direction.to_string(fling_gesture_direction.Left),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    fling_gesture.render(mod, attributes)
    |> should.equal(expected)
  })
}
