//// FocusTrap unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/focus_trap

pub fn focus_trap_render_test() {
  let mod = focus_trap.new(focus_trap.IsNotDisabled)
  let mod_disabled = focus_trap.new(focus_trap.IsDisabled)

  let cases = [
    #(#(mod, [], []), element.element("m3e-focus-trap", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-focus-trap", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-focus-trap", [], [html.br([])]),
    ),

    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-focus-trap",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    focus_trap.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
