//// MenuItemGroup unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/menu_item_group

pub fn menu_item_group_render_test() {
  let mod = menu_item_group.new()

  let cases = [
    #(#(mod, [], []), element.element("m3e-menu-item-group", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-menu-item-group", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-menu-item-group", [], [html.br([])]),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    menu_item_group.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
