//// Menu unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/menu.{Config}
import m3e/menu_position_x
import m3e/menu_position_y
import m3e/menu_variant

pub fn menu_default_config_test() {
  let cases = [
    Config(
      position_x: menu_position_x.After,
      position_y: menu_position_y.Below,
      variant: menu_variant.Standard,
      submenu: menu.IsNotSubmenu,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    menu.default_config()
    |> should.equal(expected)
  })
}

pub fn menu_from_config_test() {
  let cases = [
    #(
      menu.Config(
        position_x: menu_position_x.Before,
        position_y: menu_position_y.Above,
        variant: menu_variant.Vibrant,
        submenu: menu.IsSubmenu,
      ),
      menu.new()
        |> menu.position_x(menu_position_x.Before)
        |> menu.position_y(menu_position_y.Above)
        |> menu.variant(menu_variant.Vibrant)
        |> menu.submenu(menu.IsSubmenu),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    menu.from_config(config)
    |> should.equal(expected)
  })
}

pub fn menu_new_test() {
  let cases = [
    menu.from_config(menu.Config(
      position_x: menu_position_x.After,
      position_y: menu_position_y.Below,
      variant: menu_variant.Standard,
      submenu: menu.IsNotSubmenu,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    menu.new()
    |> should.equal(expected)
  })
}

pub fn menu_position_x_test() {
  let mod = menu.new()
  let cases = [
    #(
      menu_position_x.Before,
      menu.from_config(
        menu.Config(..menu.default_config(), position_x: menu_position_x.Before),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    menu.position_x(mod, field)
    |> should.equal(expected)
  })
}

pub fn menu_position_y_test() {
  let mod = menu.new()
  let cases = [
    #(
      menu_position_y.Above,
      menu.from_config(
        menu.Config(..menu.default_config(), position_y: menu_position_y.Above),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    menu.position_y(mod, field)
    |> should.equal(expected)
  })
}

pub fn menu_variant_test() {
  let mod = menu.new()
  let cases = [
    #(
      menu_variant.Vibrant,
      menu.from_config(
        menu.Config(..menu.default_config(), variant: menu_variant.Vibrant),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    menu.variant(mod, field)
    |> should.equal(expected)
  })
}

pub fn menu_submenu_test() {
  let mod = menu.new()
  let cases = [
    #(
      menu.IsSubmenu,
      menu.from_config(
        menu.Config(..menu.default_config(), submenu: menu.IsSubmenu),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    menu.submenu(mod, field)
    |> should.equal(expected)
  })
}

pub fn menu_render_test() {
  let mod = menu.new()

  let mod_position_x = menu.new() |> menu.position_x(menu_position_x.Before)
  let mod_position_y = menu.new() |> menu.position_y(menu_position_y.Above)
  let mod_variant = menu.new() |> menu.variant(menu_variant.Vibrant)
  let mod_submenu = menu.new() |> menu.submenu(menu.IsSubmenu)

  let cases = [
    #(#(mod, [], []), element.element("m3e-menu", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-menu", [attribute.id("id")], []),
    ),
    #(#(mod, [], [html.br([])]), element.element("m3e-menu", [], [html.br([])])),

    #(
      #(mod_position_x, [], []),
      element.element(
        "m3e-menu",
        [
          attribute.attribute(
            "position-x",
            menu_position_x.to_string(menu_position_x.Before),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_position_y, [], []),
      element.element(
        "m3e-menu",
        [
          attribute.attribute(
            "position-y",
            menu_position_y.to_string(menu_position_y.Above),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_variant, [], []),
      element.element(
        "m3e-menu",
        [
          attribute.attribute(
            "variant",
            menu_variant.to_string(menu_variant.Vibrant),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_submenu, [], []),
      element.element("m3e-menu", [attribute.attribute("submenu", "")], []),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    menu.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
