//// Mlist unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/list_variant
import m3e/mlist

pub fn mlist_render_test() {
  let mod = mlist.new(list_variant.Standard)
  let mod_variant = mlist.new(list_variant.Segmented)

  let cases = [
    #(#(mod, [], []), element.element("m3e-list", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-list", [attribute.id("id")], []),
    ),
    #(#(mod, [], [html.br([])]), element.element("m3e-list", [], [html.br([])])),

    #(
      #(mod_variant, [], []),
      element.element(
        "m3e-list",
        [
          attribute.attribute(
            "variant",
            list_variant.to_string(list_variant.Segmented),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    mlist.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
