//// OptGroup unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/opt_group

pub fn opt_group_render_test() {
  let mod = opt_group.new()

  let cases = [
    #(#(mod, [], []), element.element("m3e-optgroup", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-optgroup", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-optgroup", [], [html.br([])]),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    opt_group.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn opt_group_slot_test() {
  let cases = [
    #(opt_group.Label, attribute.attribute("slot", "label")),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    opt_group.slot(s)
    |> should.equal(expected)
  })
}
