//// OptionPanel unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/floating_panel_scroll_strategy
import m3e/option_panel.{Config}
import m3e/option_panel_state

pub fn option_panel_default_config_test() {
  let cases = [
    Config(
      state: option_panel_state.Content,
      scroll_strategy: floating_panel_scroll_strategy.Hide,
      fit_anchor_width: option_panel.IsNotFitAnchorWidth,
      anchor_offset: 0.0,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    option_panel.default_config()
    |> should.equal(expected)
  })
}

pub fn option_panel_from_config_test() {
  let cases = [
    #(
      option_panel.Config(
        state: option_panel_state.Loading,
        scroll_strategy: floating_panel_scroll_strategy.Reposition,
        fit_anchor_width: option_panel.IsFitAnchorWidth,
        anchor_offset: 42.0,
      ),
      option_panel.new()
        |> option_panel.state(option_panel_state.Loading)
        |> option_panel.scroll_strategy(
          floating_panel_scroll_strategy.Reposition,
        )
        |> option_panel.fit_anchor_width(option_panel.IsFitAnchorWidth)
        |> option_panel.anchor_offset(42.0),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    option_panel.from_config(config)
    |> should.equal(expected)
  })
}

pub fn option_panel_new_test() {
  let cases = [
    option_panel.from_config(option_panel.Config(
      state: option_panel_state.Content,
      scroll_strategy: floating_panel_scroll_strategy.Hide,
      fit_anchor_width: option_panel.IsNotFitAnchorWidth,
      anchor_offset: 0.0,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    option_panel.new()
    |> should.equal(expected)
  })
}

pub fn option_panel_state_test() {
  let mod = option_panel.new()
  let cases = [
    #(
      option_panel_state.Loading,
      option_panel.from_config(
        option_panel.Config(
          ..option_panel.default_config(),
          state: option_panel_state.Loading,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    option_panel.state(mod, field)
    |> should.equal(expected)
  })
}

pub fn option_panel_scroll_strategy_test() {
  let mod = option_panel.new()
  let cases = [
    #(
      floating_panel_scroll_strategy.Reposition,
      option_panel.from_config(
        option_panel.Config(
          ..option_panel.default_config(),
          scroll_strategy: floating_panel_scroll_strategy.Reposition,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    option_panel.scroll_strategy(mod, field)
    |> should.equal(expected)
  })
}

pub fn option_panel_fit_anchor_width_test() {
  let mod = option_panel.new()
  let cases = [
    #(
      option_panel.IsFitAnchorWidth,
      option_panel.from_config(
        option_panel.Config(
          ..option_panel.default_config(),
          fit_anchor_width: option_panel.IsFitAnchorWidth,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    option_panel.fit_anchor_width(mod, field)
    |> should.equal(expected)
  })
}

pub fn option_panel_anchor_offset_test() {
  let mod = option_panel.new()
  let cases = [
    #(
      42.0,
      option_panel.from_config(
        option_panel.Config(
          ..option_panel.default_config(),
          anchor_offset: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    option_panel.anchor_offset(mod, field)
    |> should.equal(expected)
  })
}

pub fn option_panel_render_test() {
  let mod = option_panel.new()

  let mod_state =
    option_panel.new() |> option_panel.state(option_panel_state.Loading)
  let mod_scroll_strategy =
    option_panel.new()
    |> option_panel.scroll_strategy(floating_panel_scroll_strategy.Reposition)
  let mod_fit_anchor_width =
    option_panel.new()
    |> option_panel.fit_anchor_width(option_panel.IsFitAnchorWidth)
  let mod_anchor_offset = option_panel.new() |> option_panel.anchor_offset(42.0)

  let cases = [
    #(#(mod, [], []), element.element("m3e-option-panel", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-option-panel", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-option-panel", [], [html.br([])]),
    ),

    #(
      #(mod_state, [], []),
      element.element(
        "m3e-option-panel",
        [
          attribute.attribute(
            "state",
            option_panel_state.to_string(option_panel_state.Loading),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_scroll_strategy, [], []),
      element.element(
        "m3e-option-panel",
        [
          attribute.attribute(
            "scroll-strategy",
            floating_panel_scroll_strategy.to_string(
              floating_panel_scroll_strategy.Reposition,
            ),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_fit_anchor_width, [], []),
      element.element(
        "m3e-option-panel",
        [attribute.attribute("fit-anchor-width", "")],
        [],
      ),
    ),
    #(
      #(mod_anchor_offset, [], []),
      element.element(
        "m3e-option-panel",
        [attribute.attribute("anchor-offset", "42.0")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    option_panel.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
