//// Paginator unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/form_field_variant
import m3e/number_string
import m3e/paginator.{Config}

pub fn paginator_default_config_test() {
  let cases = [
    Config(
      disabled: paginator.IsNotDisabled,
      first_page_label: "First page",
      hide_page_size: paginator.IsNotHidePageSize,
      items_per_page_label: "Items per page:",
      last_page_label: "Last page",
      length: 0.0,
      next_page_label: "Next page",
      page_index: 0.0,
      page_size: number_string.NumberVal(50.0),
      page_sizes: "5,10,25,50,100",
      page_size_variant: form_field_variant.Outlined,
      previous_page_label: "Previous page",
      show_first_last_buttons: paginator.IsNotShowFirstLastButtons,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    paginator.default_config()
    |> should.equal(expected)
  })
}

pub fn paginator_from_config_test() {
  let cases = [
    #(
      paginator.Config(
        disabled: paginator.IsDisabled,
        first_page_label: "test",
        hide_page_size: paginator.IsHidePageSize,
        items_per_page_label: "test",
        last_page_label: "test",
        length: 42.0,
        next_page_label: "test",
        page_index: 42.0,
        page_size: number_string.StringVal("10"),
        page_sizes: "test",
        page_size_variant: form_field_variant.Filled,
        previous_page_label: "test",
        show_first_last_buttons: paginator.IsShowFirstLastButtons,
      ),
      paginator.new()
        |> paginator.disabled(paginator.IsDisabled)
        |> paginator.first_page_label("test")
        |> paginator.hide_page_size(paginator.IsHidePageSize)
        |> paginator.items_per_page_label("test")
        |> paginator.last_page_label("test")
        |> paginator.length(42.0)
        |> paginator.next_page_label("test")
        |> paginator.page_index(42.0)
        |> paginator.page_size(number_string.StringVal("10"))
        |> paginator.page_sizes("test")
        |> paginator.page_size_variant(form_field_variant.Filled)
        |> paginator.previous_page_label("test")
        |> paginator.show_first_last_buttons(paginator.IsShowFirstLastButtons),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    paginator.from_config(config)
    |> should.equal(expected)
  })
}

pub fn paginator_new_test() {
  let cases = [
    paginator.from_config(paginator.Config(
      disabled: paginator.IsNotDisabled,
      first_page_label: "First page",
      hide_page_size: paginator.IsNotHidePageSize,
      items_per_page_label: "Items per page:",
      last_page_label: "Last page",
      length: 0.0,
      next_page_label: "Next page",
      page_index: 0.0,
      page_size: number_string.NumberVal(50.0),
      page_sizes: "5,10,25,50,100",
      page_size_variant: form_field_variant.Outlined,
      previous_page_label: "Previous page",
      show_first_last_buttons: paginator.IsNotShowFirstLastButtons,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    paginator.new()
    |> should.equal(expected)
  })
}

pub fn paginator_disabled_test() {
  let mod = paginator.new()
  let cases = [
    #(
      paginator.IsDisabled,
      paginator.from_config(
        paginator.Config(
          ..paginator.default_config(),
          disabled: paginator.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_first_page_label_test() {
  let mod = paginator.new()
  let cases = [
    #(
      "test",
      paginator.from_config(
        paginator.Config(..paginator.default_config(), first_page_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.first_page_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_hide_page_size_test() {
  let mod = paginator.new()
  let cases = [
    #(
      paginator.IsHidePageSize,
      paginator.from_config(
        paginator.Config(
          ..paginator.default_config(),
          hide_page_size: paginator.IsHidePageSize,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.hide_page_size(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_items_per_page_label_test() {
  let mod = paginator.new()
  let cases = [
    #(
      "test",
      paginator.from_config(
        paginator.Config(
          ..paginator.default_config(),
          items_per_page_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.items_per_page_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_last_page_label_test() {
  let mod = paginator.new()
  let cases = [
    #(
      "test",
      paginator.from_config(
        paginator.Config(..paginator.default_config(), last_page_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.last_page_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_length_test() {
  let mod = paginator.new()
  let cases = [
    #(
      42.0,
      paginator.from_config(
        paginator.Config(..paginator.default_config(), length: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.length(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_next_page_label_test() {
  let mod = paginator.new()
  let cases = [
    #(
      "test",
      paginator.from_config(
        paginator.Config(..paginator.default_config(), next_page_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.next_page_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_page_index_test() {
  let mod = paginator.new()
  let cases = [
    #(
      42.0,
      paginator.from_config(
        paginator.Config(..paginator.default_config(), page_index: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.page_index(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_page_size_test() {
  let mod = paginator.new()
  let cases = [
    #(
      number_string.StringVal("10"),
      paginator.from_config(
        paginator.Config(
          ..paginator.default_config(),
          page_size: number_string.StringVal("10"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.page_size(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_page_sizes_test() {
  let mod = paginator.new()
  let cases = [
    #(
      "test",
      paginator.from_config(
        paginator.Config(..paginator.default_config(), page_sizes: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.page_sizes(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_page_size_variant_test() {
  let mod = paginator.new()
  let cases = [
    #(
      form_field_variant.Filled,
      paginator.from_config(
        paginator.Config(
          ..paginator.default_config(),
          page_size_variant: form_field_variant.Filled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.page_size_variant(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_previous_page_label_test() {
  let mod = paginator.new()
  let cases = [
    #(
      "test",
      paginator.from_config(
        paginator.Config(
          ..paginator.default_config(),
          previous_page_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.previous_page_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_show_first_last_buttons_test() {
  let mod = paginator.new()
  let cases = [
    #(
      paginator.IsShowFirstLastButtons,
      paginator.from_config(
        paginator.Config(
          ..paginator.default_config(),
          show_first_last_buttons: paginator.IsShowFirstLastButtons,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    paginator.show_first_last_buttons(mod, field)
    |> should.equal(expected)
  })
}

pub fn paginator_render_test() {
  let mod = paginator.new()

  let mod_disabled = paginator.new() |> paginator.disabled(paginator.IsDisabled)
  let mod_first_page_label =
    paginator.new() |> paginator.first_page_label("test")
  let mod_hide_page_size =
    paginator.new() |> paginator.hide_page_size(paginator.IsHidePageSize)
  let mod_items_per_page_label =
    paginator.new() |> paginator.items_per_page_label("test")
  let mod_last_page_label = paginator.new() |> paginator.last_page_label("test")
  let mod_length = paginator.new() |> paginator.length(42.0)
  let mod_next_page_label = paginator.new() |> paginator.next_page_label("test")
  let mod_page_index = paginator.new() |> paginator.page_index(42.0)
  let mod_page_size =
    paginator.new() |> paginator.page_size(number_string.StringVal("10"))
  let mod_page_sizes = paginator.new() |> paginator.page_sizes("test")
  let mod_page_size_variant =
    paginator.new() |> paginator.page_size_variant(form_field_variant.Filled)
  let mod_previous_page_label =
    paginator.new() |> paginator.previous_page_label("test")
  let mod_show_first_last_buttons =
    paginator.new()
    |> paginator.show_first_last_buttons(paginator.IsShowFirstLastButtons)

  let cases = [
    #(#(mod, [], []), element.element("m3e-paginator", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-paginator", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-paginator", [], [html.br([])]),
    ),

    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_first_page_label, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("first-page-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_hide_page_size, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("hide-page-size", "")],
        [],
      ),
    ),
    #(
      #(mod_items_per_page_label, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("items-per-page-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_last_page_label, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("last-page-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_length, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("length", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_next_page_label, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("next-page-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_page_index, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("page-index", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_page_size, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("page-size", "10")],
        [],
      ),
    ),
    #(
      #(mod_page_sizes, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("page-sizes", "test")],
        [],
      ),
    ),
    #(
      #(mod_page_size_variant, [], []),
      element.element(
        "m3e-paginator",
        [
          attribute.attribute(
            "page-size-variant",
            form_field_variant.to_string(form_field_variant.Filled),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_previous_page_label, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("previous-page-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_show_first_last_buttons, [], []),
      element.element(
        "m3e-paginator",
        [attribute.attribute("show-first-last-buttons", "")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    paginator.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn paginator_slot_test() {
  let cases = [
    #(paginator.FirstPageIcon, attribute.attribute("slot", "first-page-icon")),
    #(
      paginator.PreviousPageIcon,
      attribute.attribute("slot", "previous-page-icon"),
    ),
    #(paginator.NextPageIcon, attribute.attribute("slot", "next-page-icon")),
    #(paginator.LastPageIcon, attribute.attribute("slot", "last-page-icon")),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    paginator.slot(s)
    |> should.equal(expected)
  })
}
