//// PanGesture unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/gesture_input_button
import m3e/pan_gesture.{Config}
import m3e/pan_gesture_lock_axis

pub fn pan_gesture_default_config_test() {
  let cases = [
    Config(
      allowed_buttons: gesture_input_button.Primary,
      disabled: pan_gesture.IsNotDisabled,
      priority: 1.0,
      min_displacement: 4.0,
      min_duration: "",
      lock_axis: pan_gesture_lock_axis.None,
      axis_threshold: 8.0,
      delta_threshold: 0.0,
      for: None,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    pan_gesture.default_config()
    |> should.equal(expected)
  })
}

pub fn pan_gesture_from_config_test() {
  let cases = [
    #(
      pan_gesture.Config(
        allowed_buttons: gesture_input_button.Secondary,
        disabled: pan_gesture.IsDisabled,
        priority: 42.0,
        min_displacement: 42.0,
        min_duration: "test",
        lock_axis: pan_gesture_lock_axis.X,
        axis_threshold: 42.0,
        delta_threshold: 42.0,
        for: Some("test"),
      ),
      pan_gesture.new()
        |> pan_gesture.allowed_buttons(gesture_input_button.Secondary)
        |> pan_gesture.disabled(pan_gesture.IsDisabled)
        |> pan_gesture.priority(42.0)
        |> pan_gesture.min_displacement(42.0)
        |> pan_gesture.min_duration("test")
        |> pan_gesture.lock_axis(pan_gesture_lock_axis.X)
        |> pan_gesture.axis_threshold(42.0)
        |> pan_gesture.delta_threshold(42.0)
        |> pan_gesture.for(Some("test")),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    pan_gesture.from_config(config)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_new_test() {
  let cases = [
    pan_gesture.from_config(pan_gesture.Config(
      allowed_buttons: gesture_input_button.Primary,
      disabled: pan_gesture.IsNotDisabled,
      priority: 1.0,
      min_displacement: 4.0,
      min_duration: "",
      lock_axis: pan_gesture_lock_axis.None,
      axis_threshold: 8.0,
      delta_threshold: 0.0,
      for: None,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    pan_gesture.new()
    |> should.equal(expected)
  })
}

pub fn pan_gesture_allowed_buttons_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      gesture_input_button.Secondary,
      pan_gesture.from_config(
        pan_gesture.Config(
          ..pan_gesture.default_config(),
          allowed_buttons: gesture_input_button.Secondary,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.allowed_buttons(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_disabled_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      pan_gesture.IsDisabled,
      pan_gesture.from_config(
        pan_gesture.Config(
          ..pan_gesture.default_config(),
          disabled: pan_gesture.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_priority_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      42.0,
      pan_gesture.from_config(
        pan_gesture.Config(..pan_gesture.default_config(), priority: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.priority(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_min_displacement_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      42.0,
      pan_gesture.from_config(
        pan_gesture.Config(
          ..pan_gesture.default_config(),
          min_displacement: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.min_displacement(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_min_duration_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      "test",
      pan_gesture.from_config(
        pan_gesture.Config(..pan_gesture.default_config(), min_duration: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.min_duration(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_lock_axis_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      pan_gesture_lock_axis.X,
      pan_gesture.from_config(
        pan_gesture.Config(
          ..pan_gesture.default_config(),
          lock_axis: pan_gesture_lock_axis.X,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.lock_axis(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_axis_threshold_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      42.0,
      pan_gesture.from_config(
        pan_gesture.Config(..pan_gesture.default_config(), axis_threshold: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.axis_threshold(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_delta_threshold_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      42.0,
      pan_gesture.from_config(
        pan_gesture.Config(
          ..pan_gesture.default_config(),
          delta_threshold: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.delta_threshold(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_for_test() {
  let mod = pan_gesture.new()
  let cases = [
    #(
      Some("test"),
      pan_gesture.from_config(
        pan_gesture.Config(..pan_gesture.default_config(), for: Some("test")),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    pan_gesture.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn pan_gesture_render_test() {
  let mod = pan_gesture.new()

  let mod_allowed_buttons =
    pan_gesture.new()
    |> pan_gesture.allowed_buttons(gesture_input_button.Secondary)
  let mod_disabled =
    pan_gesture.new() |> pan_gesture.disabled(pan_gesture.IsDisabled)
  let mod_priority = pan_gesture.new() |> pan_gesture.priority(42.0)
  let mod_min_displacement =
    pan_gesture.new() |> pan_gesture.min_displacement(42.0)
  let mod_min_duration = pan_gesture.new() |> pan_gesture.min_duration("test")
  let mod_lock_axis =
    pan_gesture.new() |> pan_gesture.lock_axis(pan_gesture_lock_axis.X)
  let mod_axis_threshold = pan_gesture.new() |> pan_gesture.axis_threshold(42.0)
  let mod_delta_threshold =
    pan_gesture.new() |> pan_gesture.delta_threshold(42.0)
  let mod_for = pan_gesture.new() |> pan_gesture.for(Some("test"))
  let cases = [
    #(#(mod, []), element.element("m3e-pan-gesture", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-pan-gesture", [attribute.id("id")], []),
    ),

    #(
      #(mod_allowed_buttons, []),
      element.element(
        "m3e-pan-gesture",
        [
          attribute.attribute(
            "allowed-buttons",
            gesture_input_button.to_string(gesture_input_button.Secondary),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_disabled, []),
      element.element(
        "m3e-pan-gesture",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_priority, []),
      element.element(
        "m3e-pan-gesture",
        [attribute.attribute("priority", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_min_displacement, []),
      element.element(
        "m3e-pan-gesture",
        [attribute.attribute("min-displacement", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_min_duration, []),
      element.element(
        "m3e-pan-gesture",
        [attribute.attribute("min-duration", "test")],
        [],
      ),
    ),
    #(
      #(mod_lock_axis, []),
      element.element(
        "m3e-pan-gesture",
        [
          attribute.attribute(
            "lock-axis",
            pan_gesture_lock_axis.to_string(pan_gesture_lock_axis.X),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_axis_threshold, []),
      element.element(
        "m3e-pan-gesture",
        [attribute.attribute("axis-threshold", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_delta_threshold, []),
      element.element(
        "m3e-pan-gesture",
        [attribute.attribute("delta-threshold", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_for, []),
      element.element(
        "m3e-pan-gesture",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    pan_gesture.render(mod, attributes)
    |> should.equal(expected)
  })
}
