//// RadioGroup unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/radio_group.{Config}

pub fn radio_group_default_config_test() {
  let cases = [
    Config(
      aria_invalid: "",
      disabled: radio_group.IsNotDisabled,
      name: "",
      required: radio_group.IsNotRequired,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    radio_group.default_config()
    |> should.equal(expected)
  })
}

pub fn radio_group_from_config_test() {
  let cases = [
    #(
      radio_group.Config(
        aria_invalid: "test",
        disabled: radio_group.IsDisabled,
        name: "test",
        required: radio_group.IsRequired,
      ),
      radio_group.new()
        |> radio_group.aria_invalid("test")
        |> radio_group.disabled(radio_group.IsDisabled)
        |> radio_group.name("test")
        |> radio_group.required(radio_group.IsRequired),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    radio_group.from_config(config)
    |> should.equal(expected)
  })
}

pub fn radio_group_new_test() {
  let cases = [
    radio_group.from_config(radio_group.Config(
      aria_invalid: "",
      disabled: radio_group.IsNotDisabled,
      name: "",
      required: radio_group.IsNotRequired,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    radio_group.new()
    |> should.equal(expected)
  })
}

pub fn radio_group_aria_invalid_test() {
  let mod = radio_group.new()
  let cases = [
    #(
      "test",
      radio_group.from_config(
        radio_group.Config(..radio_group.default_config(), aria_invalid: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    radio_group.aria_invalid(mod, field)
    |> should.equal(expected)
  })
}

pub fn radio_group_disabled_test() {
  let mod = radio_group.new()
  let cases = [
    #(
      radio_group.IsDisabled,
      radio_group.from_config(
        radio_group.Config(
          ..radio_group.default_config(),
          disabled: radio_group.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    radio_group.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn radio_group_name_test() {
  let mod = radio_group.new()
  let cases = [
    #(
      "test",
      radio_group.from_config(
        radio_group.Config(..radio_group.default_config(), name: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    radio_group.name(mod, field)
    |> should.equal(expected)
  })
}

pub fn radio_group_required_test() {
  let mod = radio_group.new()
  let cases = [
    #(
      radio_group.IsRequired,
      radio_group.from_config(
        radio_group.Config(
          ..radio_group.default_config(),
          required: radio_group.IsRequired,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    radio_group.required(mod, field)
    |> should.equal(expected)
  })
}

pub fn radio_group_render_test() {
  let mod = radio_group.new()

  let mod_aria_invalid = radio_group.new() |> radio_group.aria_invalid("test")
  let mod_disabled =
    radio_group.new() |> radio_group.disabled(radio_group.IsDisabled)
  let mod_name = radio_group.new() |> radio_group.name("test")
  let mod_required =
    radio_group.new() |> radio_group.required(radio_group.IsRequired)

  let cases = [
    #(#(mod, [], []), element.element("m3e-radio-group", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-radio-group", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-radio-group", [], [html.br([])]),
    ),

    #(
      #(mod_aria_invalid, [], []),
      element.element(
        "m3e-radio-group",
        [attribute.attribute("aria-invalid", "test")],
        [],
      ),
    ),
    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-radio-group",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_name, [], []),
      element.element(
        "m3e-radio-group",
        [attribute.attribute("name", "test")],
        [],
      ),
    ),
    #(
      #(mod_required, [], []),
      element.element(
        "m3e-radio-group",
        [attribute.attribute("required", "")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    radio_group.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
