//// RepeatGesture unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/gesture_input_button
import m3e/pointer_type
import m3e/repeat_gesture.{Config}

pub fn repeat_gesture_default_config_test() {
  let cases = [
    Config(
      for: None,
      buttons: [gesture_input_button.Primary],
      pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
      disabled: repeat_gesture.IsNotDisabled,
      priority: 1.0,
      max_interval: 250.0,
      count: 2.0,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    repeat_gesture.default_config()
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_from_config_test() {
  let cases = [
    #(
      repeat_gesture.Config(
        for: Some("test"),
        buttons: [gesture_input_button.Secondary],
        pointer_types: [pointer_type.Mouse],
        disabled: repeat_gesture.IsDisabled,
        priority: 42.0,
        max_interval: 42.0,
        count: 42.0,
      ),
      repeat_gesture.new()
        |> repeat_gesture.for(Some("test"))
        |> repeat_gesture.buttons([gesture_input_button.Secondary])
        |> repeat_gesture.pointer_types([pointer_type.Mouse])
        |> repeat_gesture.disabled(repeat_gesture.IsDisabled)
        |> repeat_gesture.priority(42.0)
        |> repeat_gesture.max_interval(42.0)
        |> repeat_gesture.count(42.0),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    repeat_gesture.from_config(config)
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_new_test() {
  let cases = [
    repeat_gesture.from_config(repeat_gesture.Config(
      for: None,
      buttons: [gesture_input_button.Primary],
      pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
      disabled: repeat_gesture.IsNotDisabled,
      priority: 1.0,
      max_interval: 250.0,
      count: 2.0,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    repeat_gesture.new()
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_for_test() {
  let mod = repeat_gesture.new()
  let cases = [
    #(
      Some("test"),
      repeat_gesture.from_config(
        repeat_gesture.Config(
          ..repeat_gesture.default_config(),
          for: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    repeat_gesture.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_buttons_test() {
  let mod = repeat_gesture.new()
  let cases = [
    #(
      [gesture_input_button.Secondary],
      repeat_gesture.from_config(
        repeat_gesture.Config(..repeat_gesture.default_config(), buttons: [
          gesture_input_button.Secondary,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    repeat_gesture.buttons(mod, field)
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_pointer_types_test() {
  let mod = repeat_gesture.new()
  let cases = [
    #(
      [pointer_type.Mouse],
      repeat_gesture.from_config(
        repeat_gesture.Config(..repeat_gesture.default_config(), pointer_types: [
          pointer_type.Mouse,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    repeat_gesture.pointer_types(mod, field)
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_disabled_test() {
  let mod = repeat_gesture.new()
  let cases = [
    #(
      repeat_gesture.IsDisabled,
      repeat_gesture.from_config(
        repeat_gesture.Config(
          ..repeat_gesture.default_config(),
          disabled: repeat_gesture.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    repeat_gesture.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_priority_test() {
  let mod = repeat_gesture.new()
  let cases = [
    #(
      42.0,
      repeat_gesture.from_config(
        repeat_gesture.Config(..repeat_gesture.default_config(), priority: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    repeat_gesture.priority(mod, field)
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_max_interval_test() {
  let mod = repeat_gesture.new()
  let cases = [
    #(
      42.0,
      repeat_gesture.from_config(
        repeat_gesture.Config(
          ..repeat_gesture.default_config(),
          max_interval: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    repeat_gesture.max_interval(mod, field)
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_count_test() {
  let mod = repeat_gesture.new()
  let cases = [
    #(
      42.0,
      repeat_gesture.from_config(
        repeat_gesture.Config(..repeat_gesture.default_config(), count: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    repeat_gesture.count(mod, field)
    |> should.equal(expected)
  })
}

pub fn repeat_gesture_render_test() {
  let mod = repeat_gesture.new()

  let mod_for = repeat_gesture.new() |> repeat_gesture.for(Some("test"))
  let mod_buttons =
    repeat_gesture.new()
    |> repeat_gesture.buttons([gesture_input_button.Secondary])
  let mod_pointer_types =
    repeat_gesture.new() |> repeat_gesture.pointer_types([pointer_type.Mouse])
  let mod_disabled =
    repeat_gesture.new() |> repeat_gesture.disabled(repeat_gesture.IsDisabled)
  let mod_priority = repeat_gesture.new() |> repeat_gesture.priority(42.0)
  let mod_max_interval =
    repeat_gesture.new() |> repeat_gesture.max_interval(42.0)
  let mod_count = repeat_gesture.new() |> repeat_gesture.count(42.0)

  let cases = [
    #(#(mod, [], []), element.element("m3e-repeat-gesture", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-repeat-gesture", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-repeat-gesture", [], [html.br([])]),
    ),

    #(
      #(mod_for, [], []),
      element.element(
        "m3e-repeat-gesture",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
    #(
      #(mod_buttons, [], []),
      element.element(
        "m3e-repeat-gesture",
        [
          attribute.attribute(
            "buttons",
            gesture_input_button.to_string(gesture_input_button.Secondary),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_pointer_types, [], []),
      element.element(
        "m3e-repeat-gesture",
        [
          attribute.attribute(
            "pointer-types",
            pointer_type.to_string(pointer_type.Mouse),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-repeat-gesture",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_priority, [], []),
      element.element(
        "m3e-repeat-gesture",
        [attribute.attribute("priority", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_max_interval, [], []),
      element.element(
        "m3e-repeat-gesture",
        [attribute.attribute("max-interval", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_count, [], []),
      element.element(
        "m3e-repeat-gesture",
        [attribute.attribute("count", "42.0")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    repeat_gesture.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
