//// RichTooltip unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/rich_tooltip.{Config}
import m3e/rich_tooltip_position
import m3e/tooltip_touch_gestures

pub fn rich_tooltip_default_config_test() {
  let cases = [
    Config(
      disabled: rich_tooltip.IsNotDisabled,
      for: None,
      hide_delay: 200.0,
      position: rich_tooltip_position.BelowAfter,
      show_delay: 0.0,
      touch_gestures: tooltip_touch_gestures.Auto,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    rich_tooltip.default_config()
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_from_config_test() {
  let cases = [
    #(
      rich_tooltip.Config(
        disabled: rich_tooltip.IsDisabled,
        for: Some("test"),
        hide_delay: 42.0,
        position: rich_tooltip_position.AboveAfter,
        show_delay: 42.0,
        touch_gestures: tooltip_touch_gestures.On,
      ),
      rich_tooltip.new()
        |> rich_tooltip.disabled(rich_tooltip.IsDisabled)
        |> rich_tooltip.for(Some("test"))
        |> rich_tooltip.hide_delay(42.0)
        |> rich_tooltip.position(rich_tooltip_position.AboveAfter)
        |> rich_tooltip.show_delay(42.0)
        |> rich_tooltip.touch_gestures(tooltip_touch_gestures.On),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    rich_tooltip.from_config(config)
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_new_test() {
  let cases = [
    rich_tooltip.from_config(rich_tooltip.Config(
      disabled: rich_tooltip.IsNotDisabled,
      for: None,
      hide_delay: 200.0,
      position: rich_tooltip_position.BelowAfter,
      show_delay: 0.0,
      touch_gestures: tooltip_touch_gestures.Auto,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    rich_tooltip.new()
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_disabled_test() {
  let mod = rich_tooltip.new()
  let cases = [
    #(
      rich_tooltip.IsDisabled,
      rich_tooltip.from_config(
        rich_tooltip.Config(
          ..rich_tooltip.default_config(),
          disabled: rich_tooltip.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    rich_tooltip.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_for_test() {
  let mod = rich_tooltip.new()
  let cases = [
    #(
      Some("test"),
      rich_tooltip.from_config(
        rich_tooltip.Config(..rich_tooltip.default_config(), for: Some("test")),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    rich_tooltip.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_hide_delay_test() {
  let mod = rich_tooltip.new()
  let cases = [
    #(
      42.0,
      rich_tooltip.from_config(
        rich_tooltip.Config(..rich_tooltip.default_config(), hide_delay: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    rich_tooltip.hide_delay(mod, field)
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_position_test() {
  let mod = rich_tooltip.new()
  let cases = [
    #(
      rich_tooltip_position.AboveAfter,
      rich_tooltip.from_config(
        rich_tooltip.Config(
          ..rich_tooltip.default_config(),
          position: rich_tooltip_position.AboveAfter,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    rich_tooltip.position(mod, field)
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_show_delay_test() {
  let mod = rich_tooltip.new()
  let cases = [
    #(
      42.0,
      rich_tooltip.from_config(
        rich_tooltip.Config(..rich_tooltip.default_config(), show_delay: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    rich_tooltip.show_delay(mod, field)
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_touch_gestures_test() {
  let mod = rich_tooltip.new()
  let cases = [
    #(
      tooltip_touch_gestures.On,
      rich_tooltip.from_config(
        rich_tooltip.Config(
          ..rich_tooltip.default_config(),
          touch_gestures: tooltip_touch_gestures.On,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    rich_tooltip.touch_gestures(mod, field)
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_render_test() {
  let mod = rich_tooltip.new()

  let mod_disabled =
    rich_tooltip.new() |> rich_tooltip.disabled(rich_tooltip.IsDisabled)
  let mod_for = rich_tooltip.new() |> rich_tooltip.for(Some("test"))
  let mod_hide_delay = rich_tooltip.new() |> rich_tooltip.hide_delay(42.0)
  let mod_position =
    rich_tooltip.new()
    |> rich_tooltip.position(rich_tooltip_position.AboveAfter)
  let mod_show_delay = rich_tooltip.new() |> rich_tooltip.show_delay(42.0)
  let mod_touch_gestures =
    rich_tooltip.new() |> rich_tooltip.touch_gestures(tooltip_touch_gestures.On)

  let cases = [
    #(#(mod, [], []), element.element("m3e-rich-tooltip", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-rich-tooltip", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-rich-tooltip", [], [html.br([])]),
    ),

    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-rich-tooltip",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_for, [], []),
      element.element(
        "m3e-rich-tooltip",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
    #(
      #(mod_hide_delay, [], []),
      element.element(
        "m3e-rich-tooltip",
        [attribute.attribute("hide-delay", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_position, [], []),
      element.element(
        "m3e-rich-tooltip",
        [
          attribute.attribute(
            "position",
            rich_tooltip_position.to_string(rich_tooltip_position.AboveAfter),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_show_delay, [], []),
      element.element(
        "m3e-rich-tooltip",
        [attribute.attribute("show-delay", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_touch_gestures, [], []),
      element.element(
        "m3e-rich-tooltip",
        [
          attribute.attribute(
            "touch-gestures",
            tooltip_touch_gestures.to_string(tooltip_touch_gestures.On),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    rich_tooltip.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn rich_tooltip_slot_test() {
  let cases = [
    #(rich_tooltip.Subhead, attribute.attribute("slot", "subhead")),
    #(rich_tooltip.Actions, attribute.attribute("slot", "actions")),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    rich_tooltip.slot(s)
    |> should.equal(expected)
  })
}
