//// RichTooltipAction unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/rich_tooltip_action

pub fn rich_tooltip_action_render_test() {
  let mod =
    rich_tooltip_action.new(rich_tooltip_action.IsNotDisableRestoreFocus)
  let mod_disable_restore_focus =
    rich_tooltip_action.new(rich_tooltip_action.IsDisableRestoreFocus)

  let cases = [
    #(#(mod, [], []), element.element("m3e-rich-tooltip-action", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-rich-tooltip-action", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-rich-tooltip-action", [], [html.br([])]),
    ),

    #(
      #(mod_disable_restore_focus, [], []),
      element.element(
        "m3e-rich-tooltip-action",
        [attribute.attribute("disable-restore-focus", "")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    rich_tooltip_action.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
