//// ScaleGesture unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/gesture_input_button
import m3e/pointer_type
import m3e/scale_gesture.{Config}

pub fn scale_gesture_default_config_test() {
  let cases = [
    Config(
      for: None,
      buttons: [gesture_input_button.Primary],
      pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
      disabled: scale_gesture.IsNotDisabled,
      priority: "1",
      pointers: 2.0,
      min_displacement: 4.0,
      max_press_interval: 120.0,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    scale_gesture.default_config()
    |> should.equal(expected)
  })
}

pub fn scale_gesture_from_config_test() {
  let cases = [
    #(
      scale_gesture.Config(
        for: Some("test"),
        buttons: [gesture_input_button.Secondary],
        pointer_types: [pointer_type.Mouse],
        disabled: scale_gesture.IsDisabled,
        priority: "test",
        pointers: 42.0,
        min_displacement: 42.0,
        max_press_interval: 42.0,
      ),
      scale_gesture.new()
        |> scale_gesture.for(Some("test"))
        |> scale_gesture.buttons([gesture_input_button.Secondary])
        |> scale_gesture.pointer_types([pointer_type.Mouse])
        |> scale_gesture.disabled(scale_gesture.IsDisabled)
        |> scale_gesture.priority("test")
        |> scale_gesture.pointers(42.0)
        |> scale_gesture.min_displacement(42.0)
        |> scale_gesture.max_press_interval(42.0),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    scale_gesture.from_config(config)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_new_test() {
  let cases = [
    scale_gesture.from_config(scale_gesture.Config(
      for: None,
      buttons: [gesture_input_button.Primary],
      pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
      disabled: scale_gesture.IsNotDisabled,
      priority: "1",
      pointers: 2.0,
      min_displacement: 4.0,
      max_press_interval: 120.0,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    scale_gesture.new()
    |> should.equal(expected)
  })
}

pub fn scale_gesture_for_test() {
  let mod = scale_gesture.new()
  let cases = [
    #(
      Some("test"),
      scale_gesture.from_config(
        scale_gesture.Config(
          ..scale_gesture.default_config(),
          for: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    scale_gesture.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_buttons_test() {
  let mod = scale_gesture.new()
  let cases = [
    #(
      [gesture_input_button.Secondary],
      scale_gesture.from_config(
        scale_gesture.Config(..scale_gesture.default_config(), buttons: [
          gesture_input_button.Secondary,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    scale_gesture.buttons(mod, field)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_pointer_types_test() {
  let mod = scale_gesture.new()
  let cases = [
    #(
      [pointer_type.Mouse],
      scale_gesture.from_config(
        scale_gesture.Config(..scale_gesture.default_config(), pointer_types: [
          pointer_type.Mouse,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    scale_gesture.pointer_types(mod, field)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_disabled_test() {
  let mod = scale_gesture.new()
  let cases = [
    #(
      scale_gesture.IsDisabled,
      scale_gesture.from_config(
        scale_gesture.Config(
          ..scale_gesture.default_config(),
          disabled: scale_gesture.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    scale_gesture.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_priority_test() {
  let mod = scale_gesture.new()
  let cases = [
    #(
      "test",
      scale_gesture.from_config(
        scale_gesture.Config(..scale_gesture.default_config(), priority: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    scale_gesture.priority(mod, field)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_pointers_test() {
  let mod = scale_gesture.new()
  let cases = [
    #(
      42.0,
      scale_gesture.from_config(
        scale_gesture.Config(..scale_gesture.default_config(), pointers: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    scale_gesture.pointers(mod, field)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_min_displacement_test() {
  let mod = scale_gesture.new()
  let cases = [
    #(
      42.0,
      scale_gesture.from_config(
        scale_gesture.Config(
          ..scale_gesture.default_config(),
          min_displacement: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    scale_gesture.min_displacement(mod, field)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_max_press_interval_test() {
  let mod = scale_gesture.new()
  let cases = [
    #(
      42.0,
      scale_gesture.from_config(
        scale_gesture.Config(
          ..scale_gesture.default_config(),
          max_press_interval: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    scale_gesture.max_press_interval(mod, field)
    |> should.equal(expected)
  })
}

pub fn scale_gesture_render_test() {
  let mod = scale_gesture.new()

  let mod_for = scale_gesture.new() |> scale_gesture.for(Some("test"))
  let mod_buttons =
    scale_gesture.new()
    |> scale_gesture.buttons([gesture_input_button.Secondary])
  let mod_pointer_types =
    scale_gesture.new() |> scale_gesture.pointer_types([pointer_type.Mouse])
  let mod_disabled =
    scale_gesture.new() |> scale_gesture.disabled(scale_gesture.IsDisabled)
  let mod_priority = scale_gesture.new() |> scale_gesture.priority("test")
  let mod_pointers = scale_gesture.new() |> scale_gesture.pointers(42.0)
  let mod_min_displacement =
    scale_gesture.new() |> scale_gesture.min_displacement(42.0)
  let mod_max_press_interval =
    scale_gesture.new() |> scale_gesture.max_press_interval(42.0)
  let cases = [
    #(#(mod, []), element.element("m3e-scale-gesture", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-scale-gesture", [attribute.id("id")], []),
    ),

    #(
      #(mod_for, []),
      element.element(
        "m3e-scale-gesture",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
    #(
      #(mod_buttons, []),
      element.element(
        "m3e-scale-gesture",
        [
          attribute.attribute(
            "buttons",
            gesture_input_button.to_string(gesture_input_button.Secondary),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_pointer_types, []),
      element.element(
        "m3e-scale-gesture",
        [
          attribute.attribute(
            "pointer-types",
            pointer_type.to_string(pointer_type.Mouse),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_disabled, []),
      element.element(
        "m3e-scale-gesture",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_priority, []),
      element.element(
        "m3e-scale-gesture",
        [attribute.attribute("priority", "test")],
        [],
      ),
    ),
    #(
      #(mod_pointers, []),
      element.element(
        "m3e-scale-gesture",
        [attribute.attribute("pointers", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_min_displacement, []),
      element.element(
        "m3e-scale-gesture",
        [attribute.attribute("min-displacement", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_max_press_interval, []),
      element.element(
        "m3e-scale-gesture",
        [attribute.attribute("max-press-interval", "42.0")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    scale_gesture.render(mod, attributes)
    |> should.equal(expected)
  })
}
