//// SearchView unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/search_view.{Config}
import m3e/search_view_mode

pub fn search_view_default_config_test() {
  let cases = [
    Config(
      contained: search_view.IsNotContained,
      mode: search_view_mode.Docked,
      open: search_view.IsNotOpen,
      clear_label: "Clear",
      close_label: "Close",
      hide_search_icon: search_view.IsNotHideSearchIcon,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    search_view.default_config()
    |> should.equal(expected)
  })
}

pub fn search_view_from_config_test() {
  let cases = [
    #(
      search_view.Config(
        contained: search_view.IsContained,
        mode: search_view_mode.Fullscreen,
        open: search_view.IsOpen,
        clear_label: "test",
        close_label: "test",
        hide_search_icon: search_view.IsHideSearchIcon,
      ),
      search_view.new()
        |> search_view.contained(search_view.IsContained)
        |> search_view.mode(search_view_mode.Fullscreen)
        |> search_view.open(search_view.IsOpen)
        |> search_view.clear_label("test")
        |> search_view.close_label("test")
        |> search_view.hide_search_icon(search_view.IsHideSearchIcon),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    search_view.from_config(config)
    |> should.equal(expected)
  })
}

pub fn search_view_new_test() {
  let cases = [
    search_view.from_config(search_view.Config(
      contained: search_view.IsNotContained,
      mode: search_view_mode.Docked,
      open: search_view.IsNotOpen,
      clear_label: "Clear",
      close_label: "Close",
      hide_search_icon: search_view.IsNotHideSearchIcon,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    search_view.new()
    |> should.equal(expected)
  })
}

pub fn search_view_contained_test() {
  let mod = search_view.new()
  let cases = [
    #(
      search_view.IsContained,
      search_view.from_config(
        search_view.Config(
          ..search_view.default_config(),
          contained: search_view.IsContained,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    search_view.contained(mod, field)
    |> should.equal(expected)
  })
}

pub fn search_view_mode_test() {
  let mod = search_view.new()
  let cases = [
    #(
      search_view_mode.Fullscreen,
      search_view.from_config(
        search_view.Config(
          ..search_view.default_config(),
          mode: search_view_mode.Fullscreen,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    search_view.mode(mod, field)
    |> should.equal(expected)
  })
}

pub fn search_view_open_test() {
  let mod = search_view.new()
  let cases = [
    #(
      search_view.IsOpen,
      search_view.from_config(
        search_view.Config(
          ..search_view.default_config(),
          open: search_view.IsOpen,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    search_view.open(mod, field)
    |> should.equal(expected)
  })
}

pub fn search_view_clear_label_test() {
  let mod = search_view.new()
  let cases = [
    #(
      "test",
      search_view.from_config(
        search_view.Config(..search_view.default_config(), clear_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    search_view.clear_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn search_view_close_label_test() {
  let mod = search_view.new()
  let cases = [
    #(
      "test",
      search_view.from_config(
        search_view.Config(..search_view.default_config(), close_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    search_view.close_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn search_view_hide_search_icon_test() {
  let mod = search_view.new()
  let cases = [
    #(
      search_view.IsHideSearchIcon,
      search_view.from_config(
        search_view.Config(
          ..search_view.default_config(),
          hide_search_icon: search_view.IsHideSearchIcon,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    search_view.hide_search_icon(mod, field)
    |> should.equal(expected)
  })
}

pub fn search_view_render_test() {
  let mod = search_view.new()

  let mod_contained =
    search_view.new() |> search_view.contained(search_view.IsContained)
  let mod_mode =
    search_view.new() |> search_view.mode(search_view_mode.Fullscreen)
  let mod_open = search_view.new() |> search_view.open(search_view.IsOpen)
  let mod_clear_label = search_view.new() |> search_view.clear_label("test")
  let mod_close_label = search_view.new() |> search_view.close_label("test")
  let mod_hide_search_icon =
    search_view.new()
    |> search_view.hide_search_icon(search_view.IsHideSearchIcon)

  let cases = [
    #(#(mod, [], []), element.element("m3e-search-view", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-search-view", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-search-view", [], [html.br([])]),
    ),

    #(
      #(mod_contained, [], []),
      element.element(
        "m3e-search-view",
        [attribute.attribute("contained", "")],
        [],
      ),
    ),
    #(
      #(mod_mode, [], []),
      element.element(
        "m3e-search-view",
        [
          attribute.attribute(
            "mode",
            search_view_mode.to_string(search_view_mode.Fullscreen),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_open, [], []),
      element.element("m3e-search-view", [attribute.attribute("open", "")], []),
    ),
    #(
      #(mod_clear_label, [], []),
      element.element(
        "m3e-search-view",
        [attribute.attribute("clear-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_close_label, [], []),
      element.element(
        "m3e-search-view",
        [attribute.attribute("close-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_hide_search_icon, [], []),
      element.element(
        "m3e-search-view",
        [attribute.attribute("hide-search-icon", "")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    search_view.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn search_view_slot_test() {
  let cases = [
    #(search_view.Input, attribute.attribute("slot", "input")),
    #(search_view.OpenLeading, attribute.attribute("slot", "open-leading")),
    #(search_view.OpenTrailing, attribute.attribute("slot", "open-trailing")),
    #(search_view.ClosedLeading, attribute.attribute("slot", "closed-leading")),
    #(
      search_view.ClosedTrailing,
      attribute.attribute("slot", "closed-trailing"),
    ),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    search_view.slot(s)
    |> should.equal(expected)
  })
}
