//// SelectionIndicator unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/selection_indicator.{Config}

pub fn selection_indicator_default_config_test() {
  let cases = [
    Config(
      bounce: selection_indicator.IsNotBounce,
      centered: selection_indicator.IsNotCentered,
      disabled: selection_indicator.IsNotDisabled,
      selected: selection_indicator.IsNotSelected,
      for: None,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    selection_indicator.default_config()
    |> should.equal(expected)
  })
}

pub fn selection_indicator_from_config_test() {
  let cases = [
    #(
      selection_indicator.Config(
        bounce: selection_indicator.IsBounce,
        centered: selection_indicator.IsCentered,
        disabled: selection_indicator.IsDisabled,
        selected: selection_indicator.IsSelected,
        for: Some("test"),
      ),
      selection_indicator.new()
        |> selection_indicator.bounce(selection_indicator.IsBounce)
        |> selection_indicator.centered(selection_indicator.IsCentered)
        |> selection_indicator.disabled(selection_indicator.IsDisabled)
        |> selection_indicator.selected(selection_indicator.IsSelected)
        |> selection_indicator.for(Some("test")),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    selection_indicator.from_config(config)
    |> should.equal(expected)
  })
}

pub fn selection_indicator_new_test() {
  let cases = [
    selection_indicator.from_config(selection_indicator.Config(
      bounce: selection_indicator.IsNotBounce,
      centered: selection_indicator.IsNotCentered,
      disabled: selection_indicator.IsNotDisabled,
      selected: selection_indicator.IsNotSelected,
      for: None,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    selection_indicator.new()
    |> should.equal(expected)
  })
}

pub fn selection_indicator_bounce_test() {
  let mod = selection_indicator.new()
  let cases = [
    #(
      selection_indicator.IsBounce,
      selection_indicator.from_config(
        selection_indicator.Config(
          ..selection_indicator.default_config(),
          bounce: selection_indicator.IsBounce,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    selection_indicator.bounce(mod, field)
    |> should.equal(expected)
  })
}

pub fn selection_indicator_centered_test() {
  let mod = selection_indicator.new()
  let cases = [
    #(
      selection_indicator.IsCentered,
      selection_indicator.from_config(
        selection_indicator.Config(
          ..selection_indicator.default_config(),
          centered: selection_indicator.IsCentered,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    selection_indicator.centered(mod, field)
    |> should.equal(expected)
  })
}

pub fn selection_indicator_disabled_test() {
  let mod = selection_indicator.new()
  let cases = [
    #(
      selection_indicator.IsDisabled,
      selection_indicator.from_config(
        selection_indicator.Config(
          ..selection_indicator.default_config(),
          disabled: selection_indicator.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    selection_indicator.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn selection_indicator_selected_test() {
  let mod = selection_indicator.new()
  let cases = [
    #(
      selection_indicator.IsSelected,
      selection_indicator.from_config(
        selection_indicator.Config(
          ..selection_indicator.default_config(),
          selected: selection_indicator.IsSelected,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    selection_indicator.selected(mod, field)
    |> should.equal(expected)
  })
}

pub fn selection_indicator_for_test() {
  let mod = selection_indicator.new()
  let cases = [
    #(
      Some("test"),
      selection_indicator.from_config(
        selection_indicator.Config(
          ..selection_indicator.default_config(),
          for: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    selection_indicator.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn selection_indicator_render_test() {
  let mod = selection_indicator.new()

  let mod_bounce =
    selection_indicator.new()
    |> selection_indicator.bounce(selection_indicator.IsBounce)
  let mod_centered =
    selection_indicator.new()
    |> selection_indicator.centered(selection_indicator.IsCentered)
  let mod_disabled =
    selection_indicator.new()
    |> selection_indicator.disabled(selection_indicator.IsDisabled)
  let mod_selected =
    selection_indicator.new()
    |> selection_indicator.selected(selection_indicator.IsSelected)
  let mod_for =
    selection_indicator.new() |> selection_indicator.for(Some("test"))
  let cases = [
    #(#(mod, []), element.element("m3e-selection-indicator", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-selection-indicator", [attribute.id("id")], []),
    ),

    #(
      #(mod_bounce, []),
      element.element(
        "m3e-selection-indicator",
        [attribute.attribute("bounce", "")],
        [],
      ),
    ),
    #(
      #(mod_centered, []),
      element.element(
        "m3e-selection-indicator",
        [attribute.attribute("centered", "")],
        [],
      ),
    ),
    #(
      #(mod_disabled, []),
      element.element(
        "m3e-selection-indicator",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_selected, []),
      element.element(
        "m3e-selection-indicator",
        [attribute.attribute("selected", "")],
        [],
      ),
    ),
    #(
      #(mod_for, []),
      element.element(
        "m3e-selection-indicator",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    selection_indicator.render(mod, attributes)
    |> should.equal(expected)
  })
}
