//// SequenceGesture unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/gesture_input_button
import m3e/sequence_gesture.{Config}

pub fn sequence_gesture_default_config_test() {
  let cases = [
    Config(
      allowed_buttons: [gesture_input_button.Primary],
      disabled: sequence_gesture.IsNotDisabled,
      priority: 1.0,
      max_interval: 250.0,
      for: None,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    sequence_gesture.default_config()
    |> should.equal(expected)
  })
}

pub fn sequence_gesture_from_config_test() {
  let cases = [
    #(
      sequence_gesture.Config(
        allowed_buttons: [gesture_input_button.Secondary],
        disabled: sequence_gesture.IsDisabled,
        priority: 42.0,
        max_interval: 42.0,
        for: Some("test"),
      ),
      sequence_gesture.new()
        |> sequence_gesture.allowed_buttons([gesture_input_button.Secondary])
        |> sequence_gesture.disabled(sequence_gesture.IsDisabled)
        |> sequence_gesture.priority(42.0)
        |> sequence_gesture.max_interval(42.0)
        |> sequence_gesture.for(Some("test")),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    sequence_gesture.from_config(config)
    |> should.equal(expected)
  })
}

pub fn sequence_gesture_new_test() {
  let cases = [
    sequence_gesture.from_config(sequence_gesture.Config(
      allowed_buttons: [gesture_input_button.Primary],
      disabled: sequence_gesture.IsNotDisabled,
      priority: 1.0,
      max_interval: 250.0,
      for: None,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    sequence_gesture.new()
    |> should.equal(expected)
  })
}

pub fn sequence_gesture_allowed_buttons_test() {
  let mod = sequence_gesture.new()
  let cases = [
    #(
      [gesture_input_button.Secondary],
      sequence_gesture.from_config(
        sequence_gesture.Config(
          ..sequence_gesture.default_config(),
          allowed_buttons: [gesture_input_button.Secondary],
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    sequence_gesture.allowed_buttons(mod, field)
    |> should.equal(expected)
  })
}

pub fn sequence_gesture_disabled_test() {
  let mod = sequence_gesture.new()
  let cases = [
    #(
      sequence_gesture.IsDisabled,
      sequence_gesture.from_config(
        sequence_gesture.Config(
          ..sequence_gesture.default_config(),
          disabled: sequence_gesture.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    sequence_gesture.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn sequence_gesture_priority_test() {
  let mod = sequence_gesture.new()
  let cases = [
    #(
      42.0,
      sequence_gesture.from_config(
        sequence_gesture.Config(
          ..sequence_gesture.default_config(),
          priority: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    sequence_gesture.priority(mod, field)
    |> should.equal(expected)
  })
}

pub fn sequence_gesture_max_interval_test() {
  let mod = sequence_gesture.new()
  let cases = [
    #(
      42.0,
      sequence_gesture.from_config(
        sequence_gesture.Config(
          ..sequence_gesture.default_config(),
          max_interval: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    sequence_gesture.max_interval(mod, field)
    |> should.equal(expected)
  })
}

pub fn sequence_gesture_for_test() {
  let mod = sequence_gesture.new()
  let cases = [
    #(
      Some("test"),
      sequence_gesture.from_config(
        sequence_gesture.Config(
          ..sequence_gesture.default_config(),
          for: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    sequence_gesture.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn sequence_gesture_render_test() {
  let mod = sequence_gesture.new()

  let mod_allowed_buttons =
    sequence_gesture.new()
    |> sequence_gesture.allowed_buttons([gesture_input_button.Secondary])
  let mod_disabled =
    sequence_gesture.new()
    |> sequence_gesture.disabled(sequence_gesture.IsDisabled)
  let mod_priority = sequence_gesture.new() |> sequence_gesture.priority(42.0)
  let mod_max_interval =
    sequence_gesture.new() |> sequence_gesture.max_interval(42.0)
  let mod_for = sequence_gesture.new() |> sequence_gesture.for(Some("test"))
  let cases = [
    #(#(mod, []), element.element("m3e-sequence-gesture", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-sequence-gesture", [attribute.id("id")], []),
    ),

    #(
      #(mod_allowed_buttons, []),
      element.element(
        "m3e-sequence-gesture",
        [
          attribute.attribute(
            "allowed-buttons",
            gesture_input_button.to_string(gesture_input_button.Secondary),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_disabled, []),
      element.element(
        "m3e-sequence-gesture",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_priority, []),
      element.element(
        "m3e-sequence-gesture",
        [attribute.attribute("priority", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_max_interval, []),
      element.element(
        "m3e-sequence-gesture",
        [attribute.attribute("max-interval", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_for, []),
      element.element(
        "m3e-sequence-gesture",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    sequence_gesture.render(mod, attributes)
    |> should.equal(expected)
  })
}
