//// Shape unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/shape
import m3e/shape_name

pub fn shape_render_test() {
  let mod = shape.new(None)
  let mod_name = shape.new(Some(shape_name.FourLeafClover))

  let cases = [
    #(#(mod, [], []), element.element("m3e-shape", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-shape", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-shape", [], [html.br([])]),
    ),

    #(
      #(mod_name, [], []),
      element.element(
        "m3e-shape",
        [
          attribute.attribute(
            "name",
            shape_name.to_string(shape_name.FourLeafClover),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    shape.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
