//// SlideGroup unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/slide_group.{Config}

pub fn slide_group_default_config_test() {
  let cases = [
    Config(
      disabled: slide_group.IsNotDisabled,
      next_page_label: "Next page",
      previous_page_label: "Previous page",
      threshold: 0.0,
      vertical: slide_group.IsNotVertical,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    slide_group.default_config()
    |> should.equal(expected)
  })
}

pub fn slide_group_from_config_test() {
  let cases = [
    #(
      slide_group.Config(
        disabled: slide_group.IsDisabled,
        next_page_label: "test",
        previous_page_label: "test",
        threshold: 42.0,
        vertical: slide_group.IsVertical,
      ),
      slide_group.new()
        |> slide_group.disabled(slide_group.IsDisabled)
        |> slide_group.next_page_label("test")
        |> slide_group.previous_page_label("test")
        |> slide_group.threshold(42.0)
        |> slide_group.vertical(slide_group.IsVertical),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    slide_group.from_config(config)
    |> should.equal(expected)
  })
}

pub fn slide_group_new_test() {
  let cases = [
    slide_group.from_config(slide_group.Config(
      disabled: slide_group.IsNotDisabled,
      next_page_label: "Next page",
      previous_page_label: "Previous page",
      threshold: 0.0,
      vertical: slide_group.IsNotVertical,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    slide_group.new()
    |> should.equal(expected)
  })
}

pub fn slide_group_disabled_test() {
  let mod = slide_group.new()
  let cases = [
    #(
      slide_group.IsDisabled,
      slide_group.from_config(
        slide_group.Config(
          ..slide_group.default_config(),
          disabled: slide_group.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    slide_group.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn slide_group_next_page_label_test() {
  let mod = slide_group.new()
  let cases = [
    #(
      "test",
      slide_group.from_config(
        slide_group.Config(
          ..slide_group.default_config(),
          next_page_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    slide_group.next_page_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn slide_group_previous_page_label_test() {
  let mod = slide_group.new()
  let cases = [
    #(
      "test",
      slide_group.from_config(
        slide_group.Config(
          ..slide_group.default_config(),
          previous_page_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    slide_group.previous_page_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn slide_group_threshold_test() {
  let mod = slide_group.new()
  let cases = [
    #(
      42.0,
      slide_group.from_config(
        slide_group.Config(..slide_group.default_config(), threshold: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    slide_group.threshold(mod, field)
    |> should.equal(expected)
  })
}

pub fn slide_group_vertical_test() {
  let mod = slide_group.new()
  let cases = [
    #(
      slide_group.IsVertical,
      slide_group.from_config(
        slide_group.Config(
          ..slide_group.default_config(),
          vertical: slide_group.IsVertical,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    slide_group.vertical(mod, field)
    |> should.equal(expected)
  })
}

pub fn slide_group_render_test() {
  let mod = slide_group.new()

  let mod_disabled =
    slide_group.new() |> slide_group.disabled(slide_group.IsDisabled)
  let mod_next_page_label =
    slide_group.new() |> slide_group.next_page_label("test")
  let mod_previous_page_label =
    slide_group.new() |> slide_group.previous_page_label("test")
  let mod_threshold = slide_group.new() |> slide_group.threshold(42.0)
  let mod_vertical =
    slide_group.new() |> slide_group.vertical(slide_group.IsVertical)

  let cases = [
    #(#(mod, [], []), element.element("m3e-slide-group", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-slide-group", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-slide-group", [], [html.br([])]),
    ),

    #(
      #(mod_disabled, [], []),
      element.element(
        "m3e-slide-group",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_next_page_label, [], []),
      element.element(
        "m3e-slide-group",
        [attribute.attribute("next-page-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_previous_page_label, [], []),
      element.element(
        "m3e-slide-group",
        [attribute.attribute("previous-page-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_threshold, [], []),
      element.element(
        "m3e-slide-group",
        [attribute.attribute("threshold", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_vertical, [], []),
      element.element(
        "m3e-slide-group",
        [attribute.attribute("vertical", "")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    slide_group.render(mod, attributes, children)
    |> should.equal(expected)
  })
}

pub fn slide_group_slot_test() {
  let cases = [
    #(slide_group.NextIcon, attribute.attribute("slot", "next-icon")),
    #(slide_group.PrevIcon, attribute.attribute("slot", "prev-icon")),
  ]

  list.each(cases, fn(c) {
    let #(s, expected) = c

    slide_group.slot(s)
    |> should.equal(expected)
  })
}
