//// StepperPrevious unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/stepper_previous

pub fn stepper_previous_render_test() {
  let mod = stepper_previous.new()

  let cases = [
    #(#(mod, [], []), element.element("m3e-stepper-previous", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-stepper-previous", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-stepper-previous", [], [html.br([])]),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    stepper_previous.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
