//// SwipeGesture unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/gesture_input_button
import m3e/pointer_type
import m3e/swipe_gesture.{Config}
import m3e/swipe_gesture_direction

pub fn swipe_gesture_default_config_test() {
  let cases = [
    Config(
      for: None,
      buttons: [gesture_input_button.Primary],
      pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
      disabled: swipe_gesture.IsNotDisabled,
      priority: "1",
      pointers: 1.0,
      start_threshold: 4.0,
      min_displacement: 12.0,
      min_velocity: "0.3",
      direction_threshold: "12",
      direction_grace_period: 0.0,
      directions: [
        swipe_gesture_direction.Left,
        swipe_gesture_direction.Right,
        swipe_gesture_direction.Up,
        swipe_gesture_direction.Down,
      ],
      max_press_interval: 120.0,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    swipe_gesture.default_config()
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_from_config_test() {
  let cases = [
    #(
      swipe_gesture.Config(
        for: Some("test"),
        buttons: [gesture_input_button.Secondary],
        pointer_types: [pointer_type.Mouse],
        disabled: swipe_gesture.IsDisabled,
        priority: "test",
        pointers: 42.0,
        start_threshold: 42.0,
        min_displacement: 42.0,
        min_velocity: "test",
        direction_threshold: "test",
        direction_grace_period: 42.0,
        directions: [swipe_gesture_direction.Left],
        max_press_interval: 42.0,
      ),
      swipe_gesture.new()
        |> swipe_gesture.for(Some("test"))
        |> swipe_gesture.buttons([gesture_input_button.Secondary])
        |> swipe_gesture.pointer_types([pointer_type.Mouse])
        |> swipe_gesture.disabled(swipe_gesture.IsDisabled)
        |> swipe_gesture.priority("test")
        |> swipe_gesture.pointers(42.0)
        |> swipe_gesture.start_threshold(42.0)
        |> swipe_gesture.min_displacement(42.0)
        |> swipe_gesture.min_velocity("test")
        |> swipe_gesture.direction_threshold("test")
        |> swipe_gesture.direction_grace_period(42.0)
        |> swipe_gesture.directions([swipe_gesture_direction.Left])
        |> swipe_gesture.max_press_interval(42.0),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    swipe_gesture.from_config(config)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_new_test() {
  let cases = [
    swipe_gesture.from_config(swipe_gesture.Config(
      for: None,
      buttons: [gesture_input_button.Primary],
      pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
      disabled: swipe_gesture.IsNotDisabled,
      priority: "1",
      pointers: 1.0,
      start_threshold: 4.0,
      min_displacement: 12.0,
      min_velocity: "0.3",
      direction_threshold: "12",
      direction_grace_period: 0.0,
      directions: [
        swipe_gesture_direction.Left,
        swipe_gesture_direction.Right,
        swipe_gesture_direction.Up,
        swipe_gesture_direction.Down,
      ],
      max_press_interval: 120.0,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    swipe_gesture.new()
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_for_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      Some("test"),
      swipe_gesture.from_config(
        swipe_gesture.Config(
          ..swipe_gesture.default_config(),
          for: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_buttons_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      [gesture_input_button.Secondary],
      swipe_gesture.from_config(
        swipe_gesture.Config(..swipe_gesture.default_config(), buttons: [
          gesture_input_button.Secondary,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.buttons(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_pointer_types_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      [pointer_type.Mouse],
      swipe_gesture.from_config(
        swipe_gesture.Config(..swipe_gesture.default_config(), pointer_types: [
          pointer_type.Mouse,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.pointer_types(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_disabled_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      swipe_gesture.IsDisabled,
      swipe_gesture.from_config(
        swipe_gesture.Config(
          ..swipe_gesture.default_config(),
          disabled: swipe_gesture.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_priority_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      "test",
      swipe_gesture.from_config(
        swipe_gesture.Config(..swipe_gesture.default_config(), priority: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.priority(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_pointers_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      42.0,
      swipe_gesture.from_config(
        swipe_gesture.Config(..swipe_gesture.default_config(), pointers: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.pointers(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_start_threshold_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      42.0,
      swipe_gesture.from_config(
        swipe_gesture.Config(
          ..swipe_gesture.default_config(),
          start_threshold: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.start_threshold(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_min_displacement_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      42.0,
      swipe_gesture.from_config(
        swipe_gesture.Config(
          ..swipe_gesture.default_config(),
          min_displacement: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.min_displacement(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_min_velocity_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      "test",
      swipe_gesture.from_config(
        swipe_gesture.Config(
          ..swipe_gesture.default_config(),
          min_velocity: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.min_velocity(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_direction_threshold_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      "test",
      swipe_gesture.from_config(
        swipe_gesture.Config(
          ..swipe_gesture.default_config(),
          direction_threshold: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.direction_threshold(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_direction_grace_period_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      42.0,
      swipe_gesture.from_config(
        swipe_gesture.Config(
          ..swipe_gesture.default_config(),
          direction_grace_period: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.direction_grace_period(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_directions_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      [swipe_gesture_direction.Left],
      swipe_gesture.from_config(
        swipe_gesture.Config(..swipe_gesture.default_config(), directions: [
          swipe_gesture_direction.Left,
        ]),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.directions(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_max_press_interval_test() {
  let mod = swipe_gesture.new()
  let cases = [
    #(
      42.0,
      swipe_gesture.from_config(
        swipe_gesture.Config(
          ..swipe_gesture.default_config(),
          max_press_interval: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    swipe_gesture.max_press_interval(mod, field)
    |> should.equal(expected)
  })
}

pub fn swipe_gesture_render_test() {
  let mod = swipe_gesture.new()

  let mod_for = swipe_gesture.new() |> swipe_gesture.for(Some("test"))
  let mod_buttons =
    swipe_gesture.new()
    |> swipe_gesture.buttons([gesture_input_button.Secondary])
  let mod_pointer_types =
    swipe_gesture.new() |> swipe_gesture.pointer_types([pointer_type.Mouse])
  let mod_disabled =
    swipe_gesture.new() |> swipe_gesture.disabled(swipe_gesture.IsDisabled)
  let mod_priority = swipe_gesture.new() |> swipe_gesture.priority("test")
  let mod_pointers = swipe_gesture.new() |> swipe_gesture.pointers(42.0)
  let mod_start_threshold =
    swipe_gesture.new() |> swipe_gesture.start_threshold(42.0)
  let mod_min_displacement =
    swipe_gesture.new() |> swipe_gesture.min_displacement(42.0)
  let mod_min_velocity =
    swipe_gesture.new() |> swipe_gesture.min_velocity("test")
  let mod_direction_threshold =
    swipe_gesture.new() |> swipe_gesture.direction_threshold("test")
  let mod_direction_grace_period =
    swipe_gesture.new() |> swipe_gesture.direction_grace_period(42.0)
  let mod_directions =
    swipe_gesture.new()
    |> swipe_gesture.directions([swipe_gesture_direction.Left])
  let mod_max_press_interval =
    swipe_gesture.new() |> swipe_gesture.max_press_interval(42.0)
  let cases = [
    #(#(mod, []), element.element("m3e-swipe-gesture", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-swipe-gesture", [attribute.id("id")], []),
    ),

    #(
      #(mod_for, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
    #(
      #(mod_buttons, []),
      element.element(
        "m3e-swipe-gesture",
        [
          attribute.attribute(
            "buttons",
            gesture_input_button.to_string(gesture_input_button.Secondary),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_pointer_types, []),
      element.element(
        "m3e-swipe-gesture",
        [
          attribute.attribute(
            "pointer-types",
            pointer_type.to_string(pointer_type.Mouse),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_disabled, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_priority, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("priority", "test")],
        [],
      ),
    ),
    #(
      #(mod_pointers, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("pointers", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_start_threshold, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("start-threshold", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_min_displacement, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("min-displacement", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_min_velocity, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("min-velocity", "test")],
        [],
      ),
    ),
    #(
      #(mod_direction_threshold, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("direction-threshold", "test")],
        [],
      ),
    ),
    #(
      #(mod_direction_grace_period, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("direction-grace-period", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_directions, []),
      element.element(
        "m3e-swipe-gesture",
        [
          attribute.attribute(
            "directions",
            swipe_gesture_direction.to_string(swipe_gesture_direction.Left),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_max_press_interval, []),
      element.element(
        "m3e-swipe-gesture",
        [attribute.attribute("max-press-interval", "42.0")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    swipe_gesture.render(mod, attributes)
    |> should.equal(expected)
  })
}
