//// TabPanel unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/tab_panel

pub fn tab_panel_render_test() {
  let mod = tab_panel.new()

  let cases = [
    #(#(mod, [], []), element.element("m3e-tab-panel", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-tab-panel", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-tab-panel", [], [html.br([])]),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    tab_panel.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
