//// TapGesture unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/gesture_input_button
import m3e/tap_gesture.{Config}

pub fn tap_gesture_default_config_test() {
  let cases = [
    Config(
      allowed_buttons: gesture_input_button.Primary,
      disabled: tap_gesture.IsNotDisabled,
      priority: 1.0,
      pointers: 1.0,
      max_press_interval: 120.0,
      max_release_interval: 120.0,
      max_displacement: 12.0,
      max_duration: 180.0,
      for: None,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    tap_gesture.default_config()
    |> should.equal(expected)
  })
}

pub fn tap_gesture_from_config_test() {
  let cases = [
    #(
      tap_gesture.Config(
        allowed_buttons: gesture_input_button.Secondary,
        disabled: tap_gesture.IsDisabled,
        priority: 42.0,
        pointers: 42.0,
        max_press_interval: 42.0,
        max_release_interval: 42.0,
        max_displacement: 42.0,
        max_duration: 42.0,
        for: Some("test"),
      ),
      tap_gesture.new()
        |> tap_gesture.allowed_buttons(gesture_input_button.Secondary)
        |> tap_gesture.disabled(tap_gesture.IsDisabled)
        |> tap_gesture.priority(42.0)
        |> tap_gesture.pointers(42.0)
        |> tap_gesture.max_press_interval(42.0)
        |> tap_gesture.max_release_interval(42.0)
        |> tap_gesture.max_displacement(42.0)
        |> tap_gesture.max_duration(42.0)
        |> tap_gesture.for(Some("test")),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    tap_gesture.from_config(config)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_new_test() {
  let cases = [
    tap_gesture.from_config(tap_gesture.Config(
      allowed_buttons: gesture_input_button.Primary,
      disabled: tap_gesture.IsNotDisabled,
      priority: 1.0,
      pointers: 1.0,
      max_press_interval: 120.0,
      max_release_interval: 120.0,
      max_displacement: 12.0,
      max_duration: 180.0,
      for: None,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    tap_gesture.new()
    |> should.equal(expected)
  })
}

pub fn tap_gesture_allowed_buttons_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      gesture_input_button.Secondary,
      tap_gesture.from_config(
        tap_gesture.Config(
          ..tap_gesture.default_config(),
          allowed_buttons: gesture_input_button.Secondary,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.allowed_buttons(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_disabled_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      tap_gesture.IsDisabled,
      tap_gesture.from_config(
        tap_gesture.Config(
          ..tap_gesture.default_config(),
          disabled: tap_gesture.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_priority_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      42.0,
      tap_gesture.from_config(
        tap_gesture.Config(..tap_gesture.default_config(), priority: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.priority(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_pointers_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      42.0,
      tap_gesture.from_config(
        tap_gesture.Config(..tap_gesture.default_config(), pointers: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.pointers(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_max_press_interval_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      42.0,
      tap_gesture.from_config(
        tap_gesture.Config(
          ..tap_gesture.default_config(),
          max_press_interval: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.max_press_interval(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_max_release_interval_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      42.0,
      tap_gesture.from_config(
        tap_gesture.Config(
          ..tap_gesture.default_config(),
          max_release_interval: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.max_release_interval(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_max_displacement_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      42.0,
      tap_gesture.from_config(
        tap_gesture.Config(
          ..tap_gesture.default_config(),
          max_displacement: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.max_displacement(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_max_duration_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      42.0,
      tap_gesture.from_config(
        tap_gesture.Config(..tap_gesture.default_config(), max_duration: 42.0),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.max_duration(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_for_test() {
  let mod = tap_gesture.new()
  let cases = [
    #(
      Some("test"),
      tap_gesture.from_config(
        tap_gesture.Config(..tap_gesture.default_config(), for: Some("test")),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    tap_gesture.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn tap_gesture_render_test() {
  let mod = tap_gesture.new()

  let mod_allowed_buttons =
    tap_gesture.new()
    |> tap_gesture.allowed_buttons(gesture_input_button.Secondary)
  let mod_disabled =
    tap_gesture.new() |> tap_gesture.disabled(tap_gesture.IsDisabled)
  let mod_priority = tap_gesture.new() |> tap_gesture.priority(42.0)
  let mod_pointers = tap_gesture.new() |> tap_gesture.pointers(42.0)
  let mod_max_press_interval =
    tap_gesture.new() |> tap_gesture.max_press_interval(42.0)
  let mod_max_release_interval =
    tap_gesture.new() |> tap_gesture.max_release_interval(42.0)
  let mod_max_displacement =
    tap_gesture.new() |> tap_gesture.max_displacement(42.0)
  let mod_max_duration = tap_gesture.new() |> tap_gesture.max_duration(42.0)
  let mod_for = tap_gesture.new() |> tap_gesture.for(Some("test"))
  let cases = [
    #(#(mod, []), element.element("m3e-tap-gesture", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-tap-gesture", [attribute.id("id")], []),
    ),

    #(
      #(mod_allowed_buttons, []),
      element.element(
        "m3e-tap-gesture",
        [
          attribute.attribute(
            "allowed-buttons",
            gesture_input_button.to_string(gesture_input_button.Secondary),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_disabled, []),
      element.element(
        "m3e-tap-gesture",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_priority, []),
      element.element(
        "m3e-tap-gesture",
        [attribute.attribute("priority", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_pointers, []),
      element.element(
        "m3e-tap-gesture",
        [attribute.attribute("pointers", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_max_press_interval, []),
      element.element(
        "m3e-tap-gesture",
        [attribute.attribute("max-press-interval", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_max_release_interval, []),
      element.element(
        "m3e-tap-gesture",
        [attribute.attribute("max-release-interval", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_max_displacement, []),
      element.element(
        "m3e-tap-gesture",
        [attribute.attribute("max-displacement", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_max_duration, []),
      element.element(
        "m3e-tap-gesture",
        [attribute.attribute("max-duration", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_for, []),
      element.element(
        "m3e-tap-gesture",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    tap_gesture.render(mod, attributes)
    |> should.equal(expected)
  })
}
