//// TextOverflow unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/text_overflow

pub fn text_overflow_render_test() {
  let mod = text_overflow.new()

  let cases = [
    #(#(mod, [], []), element.element("m3e-text-overflow", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-text-overflow", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-text-overflow", [], [html.br([])]),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    text_overflow.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
