//// TextareaAutosize unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/textarea_autosize.{Config}

pub fn textarea_autosize_default_config_test() {
  let cases = [
    Config(
      disabled: textarea_autosize.IsNotDisabled,
      for: None,
      max_rows: 0.0,
      min_rows: 0.0,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    textarea_autosize.default_config()
    |> should.equal(expected)
  })
}

pub fn textarea_autosize_from_config_test() {
  let cases = [
    #(
      textarea_autosize.Config(
        disabled: textarea_autosize.IsDisabled,
        for: Some("test"),
        max_rows: 42.0,
        min_rows: 42.0,
      ),
      textarea_autosize.new()
        |> textarea_autosize.disabled(textarea_autosize.IsDisabled)
        |> textarea_autosize.for(Some("test"))
        |> textarea_autosize.max_rows(42.0)
        |> textarea_autosize.min_rows(42.0),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    textarea_autosize.from_config(config)
    |> should.equal(expected)
  })
}

pub fn textarea_autosize_new_test() {
  let cases = [
    textarea_autosize.from_config(textarea_autosize.Config(
      disabled: textarea_autosize.IsNotDisabled,
      for: None,
      max_rows: 0.0,
      min_rows: 0.0,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    textarea_autosize.new()
    |> should.equal(expected)
  })
}

pub fn textarea_autosize_disabled_test() {
  let mod = textarea_autosize.new()
  let cases = [
    #(
      textarea_autosize.IsDisabled,
      textarea_autosize.from_config(
        textarea_autosize.Config(
          ..textarea_autosize.default_config(),
          disabled: textarea_autosize.IsDisabled,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    textarea_autosize.disabled(mod, field)
    |> should.equal(expected)
  })
}

pub fn textarea_autosize_for_test() {
  let mod = textarea_autosize.new()
  let cases = [
    #(
      Some("test"),
      textarea_autosize.from_config(
        textarea_autosize.Config(
          ..textarea_autosize.default_config(),
          for: Some("test"),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    textarea_autosize.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn textarea_autosize_max_rows_test() {
  let mod = textarea_autosize.new()
  let cases = [
    #(
      42.0,
      textarea_autosize.from_config(
        textarea_autosize.Config(
          ..textarea_autosize.default_config(),
          max_rows: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    textarea_autosize.max_rows(mod, field)
    |> should.equal(expected)
  })
}

pub fn textarea_autosize_min_rows_test() {
  let mod = textarea_autosize.new()
  let cases = [
    #(
      42.0,
      textarea_autosize.from_config(
        textarea_autosize.Config(
          ..textarea_autosize.default_config(),
          min_rows: 42.0,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    textarea_autosize.min_rows(mod, field)
    |> should.equal(expected)
  })
}

pub fn textarea_autosize_render_test() {
  let mod = textarea_autosize.new()

  let mod_disabled =
    textarea_autosize.new()
    |> textarea_autosize.disabled(textarea_autosize.IsDisabled)
  let mod_for = textarea_autosize.new() |> textarea_autosize.for(Some("test"))
  let mod_max_rows = textarea_autosize.new() |> textarea_autosize.max_rows(42.0)
  let mod_min_rows = textarea_autosize.new() |> textarea_autosize.min_rows(42.0)
  let cases = [
    #(#(mod, []), element.element("m3e-textarea-autosize", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-textarea-autosize", [attribute.id("id")], []),
    ),

    #(
      #(mod_disabled, []),
      element.element(
        "m3e-textarea-autosize",
        [attribute.attribute("disabled", "")],
        [],
      ),
    ),
    #(
      #(mod_for, []),
      element.element(
        "m3e-textarea-autosize",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
    #(
      #(mod_max_rows, []),
      element.element(
        "m3e-textarea-autosize",
        [attribute.attribute("max-rows", "42.0")],
        [],
      ),
    ),
    #(
      #(mod_min_rows, []),
      element.element(
        "m3e-textarea-autosize",
        [attribute.attribute("min-rows", "42.0")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    textarea_autosize.render(mod, attributes)
    |> should.equal(expected)
  })
}
