//// ThemeIcon unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/color_scheme
import m3e/theme_icon.{Config}
import m3e/theme_variant

pub fn theme_icon_default_config_test() {
  let cases = [
    Config(
      color: "#6750A4",
      scheme: color_scheme.Auto,
      variant: theme_variant.Neutral,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    theme_icon.default_config()
    |> should.equal(expected)
  })
}

pub fn theme_icon_from_config_test() {
  let cases = [
    #(
      theme_icon.Config(
        color: "test",
        scheme: color_scheme.Light,
        variant: theme_variant.Monochrome,
      ),
      theme_icon.new()
        |> theme_icon.color("test")
        |> theme_icon.scheme(color_scheme.Light)
        |> theme_icon.variant(theme_variant.Monochrome),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    theme_icon.from_config(config)
    |> should.equal(expected)
  })
}

pub fn theme_icon_new_test() {
  let cases = [
    theme_icon.from_config(theme_icon.Config(
      color: "#6750A4",
      scheme: color_scheme.Auto,
      variant: theme_variant.Neutral,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    theme_icon.new()
    |> should.equal(expected)
  })
}

pub fn theme_icon_color_test() {
  let mod = theme_icon.new()
  let cases = [
    #(
      "test",
      theme_icon.from_config(
        theme_icon.Config(..theme_icon.default_config(), color: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    theme_icon.color(mod, field)
    |> should.equal(expected)
  })
}

pub fn theme_icon_scheme_test() {
  let mod = theme_icon.new()
  let cases = [
    #(
      color_scheme.Light,
      theme_icon.from_config(
        theme_icon.Config(
          ..theme_icon.default_config(),
          scheme: color_scheme.Light,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    theme_icon.scheme(mod, field)
    |> should.equal(expected)
  })
}

pub fn theme_icon_variant_test() {
  let mod = theme_icon.new()
  let cases = [
    #(
      theme_variant.Monochrome,
      theme_icon.from_config(
        theme_icon.Config(
          ..theme_icon.default_config(),
          variant: theme_variant.Monochrome,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    theme_icon.variant(mod, field)
    |> should.equal(expected)
  })
}

pub fn theme_icon_render_test() {
  let mod = theme_icon.new()

  let mod_color = theme_icon.new() |> theme_icon.color("test")
  let mod_scheme = theme_icon.new() |> theme_icon.scheme(color_scheme.Light)
  let mod_variant =
    theme_icon.new() |> theme_icon.variant(theme_variant.Monochrome)
  let cases = [
    #(#(mod, []), element.element("m3e-theme-icon", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-theme-icon", [attribute.id("id")], []),
    ),

    #(
      #(mod_color, []),
      element.element(
        "m3e-theme-icon",
        [attribute.attribute("color", "test")],
        [],
      ),
    ),
    #(
      #(mod_scheme, []),
      element.element(
        "m3e-theme-icon",
        [
          attribute.attribute(
            "scheme",
            color_scheme.to_string(color_scheme.Light),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_variant, []),
      element.element(
        "m3e-theme-icon",
        [
          attribute.attribute(
            "variant",
            theme_variant.to_string(theme_variant.Monochrome),
          ),
        ],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    theme_icon.render(mod, attributes)
    |> should.equal(expected)
  })
}
