//// Timepicker unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleam/option.{None, Some}
import gleeunit/should
import lustre/attribute
import lustre/element
import m3e/date
import m3e/time_parts
import m3e/timepicker.{Config}
import m3e/timepicker_format
import m3e/timepicker_mode
import m3e/timepicker_orientation
import m3e/timepicker_variant

pub fn timepicker_default_config_test() {
  let cases = [
    Config(
      variant: timepicker_variant.Docked,
      mode: timepicker_mode.Dial,
      orientation: timepicker_orientation.Vertical,
      date: None,
      format: timepicker_format.OneTwo,
      max_time: None,
      min_time: None,
      show_seconds: timepicker.IsNotShowSeconds,
      confirm_label: "OK",
      dismiss_label: "Cancel",
      dial_label: "Select time",
      input_label: "Edit time",
      hour_label: "Hour",
      minute_label: "Minute",
      second_label: "Second",
      mode_toggle_label: "Toggle input picker",
      hide_mode_toggle: timepicker.IsNotHideModeToggle,
      period_toggle_label: "AM or PM",
      for: None,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    timepicker.default_config()
    |> should.equal(expected)
  })
}

pub fn timepicker_from_config_test() {
  let cases = [
    #(
      timepicker.Config(
        variant: timepicker_variant.Modal,
        mode: timepicker_mode.Input,
        orientation: timepicker_orientation.Horizontal,
        date: Some(date.today_utc()),
        format: timepicker_format.TwoFour,
        max_time: Some(time_parts.zero()),
        min_time: Some(time_parts.zero()),
        show_seconds: timepicker.IsShowSeconds,
        confirm_label: "test",
        dismiss_label: "test",
        dial_label: "test",
        input_label: "test",
        hour_label: "test",
        minute_label: "test",
        second_label: "test",
        mode_toggle_label: "test",
        hide_mode_toggle: timepicker.IsHideModeToggle,
        period_toggle_label: "test",
        for: Some("test"),
      ),
      timepicker.new()
        |> timepicker.variant(timepicker_variant.Modal)
        |> timepicker.mode(timepicker_mode.Input)
        |> timepicker.orientation(timepicker_orientation.Horizontal)
        |> timepicker.date(Some(date.today_utc()))
        |> timepicker.format(timepicker_format.TwoFour)
        |> timepicker.max_time(Some(time_parts.zero()))
        |> timepicker.min_time(Some(time_parts.zero()))
        |> timepicker.show_seconds(timepicker.IsShowSeconds)
        |> timepicker.confirm_label("test")
        |> timepicker.dismiss_label("test")
        |> timepicker.dial_label("test")
        |> timepicker.input_label("test")
        |> timepicker.hour_label("test")
        |> timepicker.minute_label("test")
        |> timepicker.second_label("test")
        |> timepicker.mode_toggle_label("test")
        |> timepicker.hide_mode_toggle(timepicker.IsHideModeToggle)
        |> timepicker.period_toggle_label("test")
        |> timepicker.for(Some("test")),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    timepicker.from_config(config)
    |> should.equal(expected)
  })
}

pub fn timepicker_new_test() {
  let cases = [
    timepicker.from_config(timepicker.Config(
      variant: timepicker_variant.Docked,
      mode: timepicker_mode.Dial,
      orientation: timepicker_orientation.Vertical,
      date: None,
      format: timepicker_format.OneTwo,
      max_time: None,
      min_time: None,
      show_seconds: timepicker.IsNotShowSeconds,
      confirm_label: "OK",
      dismiss_label: "Cancel",
      dial_label: "Select time",
      input_label: "Edit time",
      hour_label: "Hour",
      minute_label: "Minute",
      second_label: "Second",
      mode_toggle_label: "Toggle input picker",
      hide_mode_toggle: timepicker.IsNotHideModeToggle,
      period_toggle_label: "AM or PM",
      for: None,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    timepicker.new()
    |> should.equal(expected)
  })
}

pub fn timepicker_variant_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      timepicker_variant.Modal,
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          variant: timepicker_variant.Modal,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.variant(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_mode_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      timepicker_mode.Input,
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          mode: timepicker_mode.Input,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.mode(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_orientation_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      timepicker_orientation.Horizontal,
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          orientation: timepicker_orientation.Horizontal,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.orientation(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_date_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      Some(date.today_utc()),
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          date: Some(date.today_utc()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.date(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_format_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      timepicker_format.TwoFour,
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          format: timepicker_format.TwoFour,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.format(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_max_time_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      Some(time_parts.zero()),
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          max_time: Some(time_parts.zero()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.max_time(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_min_time_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      Some(time_parts.zero()),
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          min_time: Some(time_parts.zero()),
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.min_time(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_show_seconds_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      timepicker.IsShowSeconds,
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          show_seconds: timepicker.IsShowSeconds,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.show_seconds(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_confirm_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(..timepicker.default_config(), confirm_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.confirm_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_dismiss_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(..timepicker.default_config(), dismiss_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.dismiss_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_dial_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(..timepicker.default_config(), dial_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.dial_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_input_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(..timepicker.default_config(), input_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.input_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_hour_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(..timepicker.default_config(), hour_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.hour_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_minute_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(..timepicker.default_config(), minute_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.minute_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_second_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(..timepicker.default_config(), second_label: "test"),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.second_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_mode_toggle_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          mode_toggle_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.mode_toggle_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_hide_mode_toggle_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      timepicker.IsHideModeToggle,
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          hide_mode_toggle: timepicker.IsHideModeToggle,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.hide_mode_toggle(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_period_toggle_label_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      "test",
      timepicker.from_config(
        timepicker.Config(
          ..timepicker.default_config(),
          period_toggle_label: "test",
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.period_toggle_label(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_for_test() {
  let mod = timepicker.new()
  let cases = [
    #(
      Some("test"),
      timepicker.from_config(
        timepicker.Config(..timepicker.default_config(), for: Some("test")),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    timepicker.for(mod, field)
    |> should.equal(expected)
  })
}

pub fn timepicker_render_test() {
  let mod = timepicker.new()

  let mod_variant =
    timepicker.new() |> timepicker.variant(timepicker_variant.Modal)
  let mod_mode = timepicker.new() |> timepicker.mode(timepicker_mode.Input)
  let mod_orientation =
    timepicker.new()
    |> timepicker.orientation(timepicker_orientation.Horizontal)
  let mod_date = timepicker.new() |> timepicker.date(Some(date.today_utc()))
  let mod_format =
    timepicker.new() |> timepicker.format(timepicker_format.TwoFour)
  let mod_max_time =
    timepicker.new() |> timepicker.max_time(Some(time_parts.zero()))
  let mod_min_time =
    timepicker.new() |> timepicker.min_time(Some(time_parts.zero()))
  let mod_show_seconds =
    timepicker.new() |> timepicker.show_seconds(timepicker.IsShowSeconds)
  let mod_confirm_label = timepicker.new() |> timepicker.confirm_label("test")
  let mod_dismiss_label = timepicker.new() |> timepicker.dismiss_label("test")
  let mod_dial_label = timepicker.new() |> timepicker.dial_label("test")
  let mod_input_label = timepicker.new() |> timepicker.input_label("test")
  let mod_hour_label = timepicker.new() |> timepicker.hour_label("test")
  let mod_minute_label = timepicker.new() |> timepicker.minute_label("test")
  let mod_second_label = timepicker.new() |> timepicker.second_label("test")
  let mod_mode_toggle_label =
    timepicker.new() |> timepicker.mode_toggle_label("test")
  let mod_hide_mode_toggle =
    timepicker.new() |> timepicker.hide_mode_toggle(timepicker.IsHideModeToggle)
  let mod_period_toggle_label =
    timepicker.new() |> timepicker.period_toggle_label("test")
  let mod_for = timepicker.new() |> timepicker.for(Some("test"))
  let cases = [
    #(#(mod, []), element.element("m3e-timepicker", [], [])),
    #(
      #(mod, [attribute.id("id")]),
      element.element("m3e-timepicker", [attribute.id("id")], []),
    ),

    #(
      #(mod_variant, []),
      element.element(
        "m3e-timepicker",
        [
          attribute.attribute(
            "variant",
            timepicker_variant.to_string(timepicker_variant.Modal),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_mode, []),
      element.element(
        "m3e-timepicker",
        [
          attribute.attribute(
            "mode",
            timepicker_mode.to_string(timepicker_mode.Input),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_orientation, []),
      element.element(
        "m3e-timepicker",
        [
          attribute.attribute(
            "orientation",
            timepicker_orientation.to_string(timepicker_orientation.Horizontal),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_date, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("date", date.to_string(date.today_utc()))],
        [],
      ),
    ),
    #(
      #(mod_format, []),
      element.element(
        "m3e-timepicker",
        [
          attribute.attribute(
            "format",
            timepicker_format.to_string(timepicker_format.TwoFour),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_max_time, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("max-time", time_parts.zero_string())],
        [],
      ),
    ),
    #(
      #(mod_min_time, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("min-time", time_parts.zero_string())],
        [],
      ),
    ),
    #(
      #(mod_show_seconds, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("show-seconds", "")],
        [],
      ),
    ),
    #(
      #(mod_confirm_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("confirm-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_dismiss_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("dismiss-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_dial_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("dial-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_input_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("input-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_hour_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("hour-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_minute_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("minute-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_second_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("second-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_mode_toggle_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("mode-toggle-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_hide_mode_toggle, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("hide-mode-toggle", "")],
        [],
      ),
    ),
    #(
      #(mod_period_toggle_label, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("period-toggle-label", "test")],
        [],
      ),
    ),
    #(
      #(mod_for, []),
      element.element(
        "m3e-timepicker",
        [attribute.attribute("for", "test")],
        [],
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes), expected) = c

    timepicker.render(mod, attributes)
    |> should.equal(expected)
  })
}
