//// Toolbar unit tests
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import gleeunit/should
import lustre/attribute
import lustre/element
import lustre/element/html
import m3e/toolbar.{Config}
import m3e/toolbar_shape
import m3e/toolbar_variant

pub fn toolbar_default_config_test() {
  let cases = [
    Config(
      elevated: toolbar.IsNotElevated,
      shape: toolbar_shape.Square,
      variant: toolbar_variant.Standard,
      vertical: toolbar.IsNotVertical,
    ),
  ]

  list.each(cases, fn(c) {
    let expected = c

    toolbar.default_config()
    |> should.equal(expected)
  })
}

pub fn toolbar_from_config_test() {
  let cases = [
    #(
      toolbar.Config(
        elevated: toolbar.IsElevated,
        shape: toolbar_shape.Rounded,
        variant: toolbar_variant.Vibrant,
        vertical: toolbar.IsVertical,
      ),
      toolbar.new()
        |> toolbar.elevated(toolbar.IsElevated)
        |> toolbar.shape(toolbar_shape.Rounded)
        |> toolbar.variant(toolbar_variant.Vibrant)
        |> toolbar.vertical(toolbar.IsVertical),
    ),
  ]

  list.each(cases, fn(c) {
    let #(config, expected) = c

    toolbar.from_config(config)
    |> should.equal(expected)
  })
}

pub fn toolbar_new_test() {
  let cases = [
    toolbar.from_config(toolbar.Config(
      elevated: toolbar.IsNotElevated,
      shape: toolbar_shape.Square,
      variant: toolbar_variant.Standard,
      vertical: toolbar.IsNotVertical,
    )),
  ]

  list.each(cases, fn(c) {
    let expected = c

    toolbar.new()
    |> should.equal(expected)
  })
}

pub fn toolbar_elevated_test() {
  let mod = toolbar.new()
  let cases = [
    #(
      toolbar.IsElevated,
      toolbar.from_config(
        toolbar.Config(..toolbar.default_config(), elevated: toolbar.IsElevated),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    toolbar.elevated(mod, field)
    |> should.equal(expected)
  })
}

pub fn toolbar_shape_test() {
  let mod = toolbar.new()
  let cases = [
    #(
      toolbar_shape.Rounded,
      toolbar.from_config(
        toolbar.Config(..toolbar.default_config(), shape: toolbar_shape.Rounded),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    toolbar.shape(mod, field)
    |> should.equal(expected)
  })
}

pub fn toolbar_variant_test() {
  let mod = toolbar.new()
  let cases = [
    #(
      toolbar_variant.Vibrant,
      toolbar.from_config(
        toolbar.Config(
          ..toolbar.default_config(),
          variant: toolbar_variant.Vibrant,
        ),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    toolbar.variant(mod, field)
    |> should.equal(expected)
  })
}

pub fn toolbar_vertical_test() {
  let mod = toolbar.new()
  let cases = [
    #(
      toolbar.IsVertical,
      toolbar.from_config(
        toolbar.Config(..toolbar.default_config(), vertical: toolbar.IsVertical),
      ),
    ),
  ]

  list.each(cases, fn(c) {
    let #(field, expected) = c

    toolbar.vertical(mod, field)
    |> should.equal(expected)
  })
}

pub fn toolbar_render_test() {
  let mod = toolbar.new()

  let mod_elevated = toolbar.new() |> toolbar.elevated(toolbar.IsElevated)
  let mod_shape = toolbar.new() |> toolbar.shape(toolbar_shape.Rounded)
  let mod_variant = toolbar.new() |> toolbar.variant(toolbar_variant.Vibrant)
  let mod_vertical = toolbar.new() |> toolbar.vertical(toolbar.IsVertical)

  let cases = [
    #(#(mod, [], []), element.element("m3e-toolbar", [], [])),
    #(
      #(mod, [attribute.id("id")], []),
      element.element("m3e-toolbar", [attribute.id("id")], []),
    ),
    #(
      #(mod, [], [html.br([])]),
      element.element("m3e-toolbar", [], [html.br([])]),
    ),

    #(
      #(mod_elevated, [], []),
      element.element("m3e-toolbar", [attribute.attribute("elevated", "")], []),
    ),
    #(
      #(mod_shape, [], []),
      element.element(
        "m3e-toolbar",
        [
          attribute.attribute(
            "shape",
            toolbar_shape.to_string(toolbar_shape.Rounded),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_variant, [], []),
      element.element(
        "m3e-toolbar",
        [
          attribute.attribute(
            "variant",
            toolbar_variant.to_string(toolbar_variant.Vibrant),
          ),
        ],
        [],
      ),
    ),
    #(
      #(mod_vertical, [], []),
      element.element("m3e-toolbar", [attribute.attribute("vertical", "")], []),
    ),
  ]

  list.each(cases, fn(c) {
    let #(#(mod, attributes, children), expected) = c

    toolbar.render(mod, attributes, children)
    |> should.equal(expected)
  })
}
