name = "m3e"
version = "1.0.0"
target = "javascript"
description = "Gleam bindings to all of the M3E components"
licences = ["MIT"]
repository = { type = "github", user = "bruceesmith", repo = "m3e" }
gleam = ">= 1.15.2 and < 2.0.0"

[dependencies]
gleam_stdlib = ">= 0.69.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"

[tools.lustre.bin]
bun = "/home/bruce/.bun/bin/bun"
