//// BadgeSize
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type BadgeSize {
  Small
  Medium
  Large
}

pub fn to_string(level: BadgeSize) -> String {
  case level {
    Small -> "small"
    Medium -> "medium"
    Large -> "large"
  }
}
