//// BottomSheetAction is an element, nested within a clickable element, used to close a parenting bottom sheet.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import lustre/attribute.{type Attribute}
import lustre/element.{type Element}

// --- Types ---

/// BottomSheetAction is a View Model for this component
///
pub opaque type BottomSheetAction {
  BottomSheetAction
}

// --- Defaults ---

// --- Constructors ---

/// new creates a new BottomSheetAction with the default configuration.
///
pub fn new() -> BottomSheetAction {
  BottomSheetAction
}

// --- Setters ---

// --- Renderers ---

/// render creates a Lustre Element for a BottomSheetAction
///
pub fn render(
  _: BottomSheetAction,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  element.element("m3e-bottom-sheet-action", attributes, children)
}
