//// BreadcrumbItemCurrent
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type BreadcrumbItemCurrent {
  Page
  Step
  Location
  Date
  Time
  True
}

pub fn to_string(level: BreadcrumbItemCurrent) -> String {
  case level {
    Page -> "page"
    Step -> "step"
    Location -> "location"
    Date -> "date"
    Time -> "time"
    True -> "true"
  }
}
