//// ButtonVariant
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type ButtonVariant {
  Elevated
  Filled
  Tonal
  Outlined
  Text
}

pub fn to_string(level: ButtonVariant) -> String {
  case level {
    Elevated -> "elevated"
    Filled -> "filled"
    Tonal -> "tonal"
    Outlined -> "outlined"
    Text -> "text"
  }
}
