//// CardOrientation
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type CardOrientation {
  Horizontal
  Vertical
}

pub fn to_string(level: CardOrientation) -> String {
  case level {
    Horizontal -> "horizontal"
    Vertical -> "vertical"
  }
}
