//// ColorScheme
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type ColorScheme {
  Light
  Dark
  Auto
}

pub fn to_string(level: ColorScheme) -> String {
  case level {
    Light -> "light"
    Dark -> "dark"
    Auto -> "auto"
  }
}
