//// DateInputTimeFormat
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type DateInputTimeFormat {
  OneTwo
  TwoFour
  Auto
}

pub fn to_string(level: DateInputTimeFormat) -> String {
  case level {
    OneTwo -> "12"
    TwoFour -> "24"
    Auto -> "auto"
  }
}
