//// DatepickerVariant
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type DatepickerVariant {
  Docked
  Modal
  Auto
}

pub fn to_string(level: DatepickerVariant) -> String {
  case level {
    Docked -> "docked"
    Modal -> "modal"
    Auto -> "auto"
  }
}
