//// DateInputType
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type DateInputType {
  Date
  Datetime
  Time
}

pub fn to_string(level: DateInputType) -> String {
  case level {
    Date -> "date"
    Datetime -> "datetime"
    Time -> "time"
  }
}
