//// DialogAction is an element, nested within a clickable element, used to close a parenting dialog.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr

// --- Types ---

/// DialogAction is a View Model for this component
///
/// ## Fields:
///
/// - return_value: The value to return from the dialog.
///
pub opaque type DialogAction {
  DialogAction(return_value: String)
}

// --- Defaults ---

pub const default_return_value: String = ""

// --- Constructors ---

/// new creates a new DialogAction with the default configuration.
///
pub fn new(return_value: String) -> DialogAction {
  DialogAction(return_value: return_value)
}

// --- Setters ---

/// return_value sets the value of return_value for this DialogAction.
///
pub fn return_value(_: DialogAction, return_value: String) -> DialogAction {
  DialogAction(return_value: return_value)
}

// --- Renderers ---

/// render creates a Lustre Element for a DialogAction
///
pub fn render(
  model: DialogAction,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  element.element(
    "m3e-dialog-action",
    list.flatten([
      [
        attr.with_default(
          "return-value",
          model.return_value,
          default_return_value,
        ),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    children,
  )
}
