//// IconVariant
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type IconVariant {
  Outlined
  Rounded
  Sharp
}

pub fn to_string(level: IconVariant) -> String {
  case level {
    Outlined -> "outlined"
    Rounded -> "rounded"
    Sharp -> "sharp"
  }
}
