//// ListVariant
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type ListVariant {
  Standard
  Segmented
}

pub fn to_string(level: ListVariant) -> String {
  case level {
    Standard -> "standard"
    Segmented -> "segmented"
  }
}
