//// LongPressGesture is a non-visual element used to detect a long-press gesture for an associated element.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/float
import gleam/function
import gleam/list
import gleam/option.{type Option, None}
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr
import m3e/gesture_input_button.{type GestureInputButton}

// --- Types ---

/// LongPressGesture is a View Model for this component
///
/// ## Fields:
///
/// - allowed_buttons: Which buttons can be pressed.
/// - disabled: Whether gesture recognition is disabled.
/// - priority: The priority in which to recognize gestures.
/// - max_displacement: Maximum distance (px) a pointer can move before the gesture fails.
/// - min_duration: Minimum time (ms) a pointer must remain pressed.
/// - for: The identifier of the interactive control to which this element is attached.
///
pub opaque type LongPressGesture {
  LongPressGesture(
    allowed_buttons: List(GestureInputButton),
    disabled: Disabled,
    priority: Float,
    max_displacement: Float,
    min_duration: Float,
    for: Option(String),
  )
}

/// Disabled is whether gesture recognition is disabled.
///
pub type Disabled {
  IsDisabled
  IsNotDisabled
}

// --- Defaults ---

pub const default_allowed_buttons: List(GestureInputButton) = [
  gesture_input_button.Primary,
]

pub const default_disabled: Disabled = IsNotDisabled

pub const default_priority: Float = 1.0

pub const default_max_displacement: Float = 4.0

pub const default_min_duration: Float = 500.0

pub const default_for: Option(String) = None

// --- Configuration ---

/// Config is a public record for configuring this component.
///
pub type Config {
  Config(
    allowed_buttons: List(GestureInputButton),
    disabled: Disabled,
    priority: Float,
    max_displacement: Float,
    min_duration: Float,
    for: Option(String),
  )
}

/// default_config is the default configuration for this component.
///
pub fn default_config() -> Config {
  Config(
    allowed_buttons: [gesture_input_button.Primary],
    disabled: IsNotDisabled,
    priority: 1.0,
    max_displacement: 4.0,
    min_duration: 500.0,
    for: None,
  )
}

// --- Constructors ---

/// from_config creates a new LongPressGesture from the given configuration.
///
pub fn from_config(config: Config) -> LongPressGesture {
  LongPressGesture(
    allowed_buttons: config.allowed_buttons,
    disabled: config.disabled,
    priority: config.priority,
    max_displacement: config.max_displacement,
    min_duration: config.min_duration,
    for: config.for,
  )
}

/// new creates a new LongPressGesture with the default configuration.
///
pub fn new() -> LongPressGesture {
  from_config(default_config())
}

// --- Setters ---

/// allowed_buttons sets the value of allowed_buttons for this LongPressGesture.
///
pub fn allowed_buttons(
  record: LongPressGesture,
  allowed_buttons: List(GestureInputButton),
) -> LongPressGesture {
  LongPressGesture(..record, allowed_buttons: allowed_buttons)
}

/// disabled sets the value of disabled for this LongPressGesture.
///
pub fn disabled(
  record: LongPressGesture,
  disabled: Disabled,
) -> LongPressGesture {
  LongPressGesture(..record, disabled: disabled)
}

/// priority sets the value of priority for this LongPressGesture.
///
pub fn priority(record: LongPressGesture, priority: Float) -> LongPressGesture {
  LongPressGesture(..record, priority: priority)
}

/// max_displacement sets the value of max_displacement for this LongPressGesture.
///
pub fn max_displacement(
  record: LongPressGesture,
  max_displacement: Float,
) -> LongPressGesture {
  LongPressGesture(..record, max_displacement: max_displacement)
}

/// min_duration sets the value of min_duration for this LongPressGesture.
///
pub fn min_duration(
  record: LongPressGesture,
  min_duration: Float,
) -> LongPressGesture {
  LongPressGesture(..record, min_duration: min_duration)
}

/// for sets the value of for for this LongPressGesture.
///
pub fn for(record: LongPressGesture, for: Option(String)) -> LongPressGesture {
  LongPressGesture(..record, for: for)
}

// --- Renderers ---

/// render creates a Lustre Element for a LongPressGesture
///
pub fn render(
  model: LongPressGesture,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  element.element(
    "m3e-long-press-gesture",
    list.flatten([
      [
        attr.with_default(
          "allowed-buttons",
          attr.list_to_spaced_string(
            model.allowed_buttons,
            gesture_input_button.to_string,
          ),
          attr.list_to_spaced_string(
            default_allowed_buttons,
            gesture_input_button.to_string,
          ),
        ),
        attr.boolean("disabled", model.disabled == IsDisabled),
        attr.with_default(
          "priority",
          float.to_string(model.priority),
          float.to_string(default_priority),
        ),
        attr.with_default(
          "max-displacement",
          float.to_string(model.max_displacement),
          float.to_string(default_max_displacement),
        ),
        attr.with_default(
          "min-duration",
          float.to_string(model.min_duration),
          float.to_string(default_min_duration),
        ),
        attr.option(model.for, fn(_) { "for" }, function.identity, default_for),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    [],
  )
}

/// render_config creates a Lustre Element from a LongPressGesture Config
///
pub fn render_config(
  c: Config,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  render(from_config(c), attributes)
}
