//// LongPressGesture is a non-visual element used to detect and interpret long-press gestures from an input stream
//// //// produced from an attached element.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/float
import gleam/function
import gleam/list
import gleam/option.{type Option, None}
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr
import m3e/gesture_input_button.{type GestureInputButton}
import m3e/pointer_type.{type PointerType}

// --- Types ---

/// LongPressGesture is a View Model for this component
///
/// ## Fields:
///
/// - for: The identifier of the interactive control to which this element is attached.
/// - buttons: Which buttons can be pressed.
/// - pointer_types: Which types of pointers can be used to recognize gestures.
/// - disabled: Whether gesture recognition is disabled.
/// - priority: The priority in which to recognize gestures.
/// - pointers: Number of pointers required for the gesture to be recognized.
/// - max_displacement: Maximum allowed movement (px).
/// - min_duration: Minimum time (ms) a pointer must remain pressed.
/// - max_press_interval: Maximum allowed time (ms) between the earliest and latest press.
///
pub opaque type LongPressGesture {
  LongPressGesture(
    for: Option(String),
    buttons: List(GestureInputButton),
    pointer_types: List(PointerType),
    disabled: Disabled,
    priority: String,
    pointers: Float,
    max_displacement: Float,
    min_duration: Float,
    max_press_interval: Float,
  )
}

/// Disabled is whether gesture recognition is disabled.
///
pub type Disabled {
  IsDisabled
  IsNotDisabled
}

// --- Defaults ---

pub const default_for: Option(String) = None

pub const default_buttons: List(GestureInputButton) = [
  gesture_input_button.Primary,
]

pub const default_pointer_types: List(PointerType) = [
  pointer_type.Mouse,
  pointer_type.Pen,
  pointer_type.Touch,
]

pub const default_disabled: Disabled = IsNotDisabled

pub const default_priority: String = "1"

pub const default_pointers: Float = 1.0

pub const default_max_displacement: Float = 4.0

pub const default_min_duration: Float = 500.0

pub const default_max_press_interval: Float = 120.0

// --- Configuration ---

/// Config is a public record for configuring this component.
///
pub type Config {
  Config(
    for: Option(String),
    buttons: List(GestureInputButton),
    pointer_types: List(PointerType),
    disabled: Disabled,
    priority: String,
    pointers: Float,
    max_displacement: Float,
    min_duration: Float,
    max_press_interval: Float,
  )
}

/// default_config is the default configuration for this component.
///
pub fn default_config() -> Config {
  Config(
    for: None,
    buttons: [gesture_input_button.Primary],
    pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
    disabled: IsNotDisabled,
    priority: "1",
    pointers: 1.0,
    max_displacement: 4.0,
    min_duration: 500.0,
    max_press_interval: 120.0,
  )
}

// --- Constructors ---

/// from_config creates a new LongPressGesture from the given configuration.
///
pub fn from_config(config: Config) -> LongPressGesture {
  LongPressGesture(
    for: config.for,
    buttons: config.buttons,
    pointer_types: config.pointer_types,
    disabled: config.disabled,
    priority: config.priority,
    pointers: config.pointers,
    max_displacement: config.max_displacement,
    min_duration: config.min_duration,
    max_press_interval: config.max_press_interval,
  )
}

/// new creates a new LongPressGesture with the default configuration.
///
pub fn new() -> LongPressGesture {
  from_config(default_config())
}

// --- Setters ---

/// for sets the value of for for this LongPressGesture.
///
pub fn for(record: LongPressGesture, for: Option(String)) -> LongPressGesture {
  LongPressGesture(..record, for: for)
}

/// buttons sets the value of buttons for this LongPressGesture.
///
pub fn buttons(
  record: LongPressGesture,
  buttons: List(GestureInputButton),
) -> LongPressGesture {
  LongPressGesture(..record, buttons: buttons)
}

/// pointer_types sets the value of pointer_types for this LongPressGesture.
///
pub fn pointer_types(
  record: LongPressGesture,
  pointer_types: List(PointerType),
) -> LongPressGesture {
  LongPressGesture(..record, pointer_types: pointer_types)
}

/// disabled sets the value of disabled for this LongPressGesture.
///
pub fn disabled(
  record: LongPressGesture,
  disabled: Disabled,
) -> LongPressGesture {
  LongPressGesture(..record, disabled: disabled)
}

/// priority sets the value of priority for this LongPressGesture.
///
pub fn priority(
  record: LongPressGesture,
  priority: String,
) -> LongPressGesture {
  LongPressGesture(..record, priority: priority)
}

/// pointers sets the value of pointers for this LongPressGesture.
///
pub fn pointers(record: LongPressGesture, pointers: Float) -> LongPressGesture {
  LongPressGesture(..record, pointers: pointers)
}

/// max_displacement sets the value of max_displacement for this LongPressGesture.
///
pub fn max_displacement(
  record: LongPressGesture,
  max_displacement: Float,
) -> LongPressGesture {
  LongPressGesture(..record, max_displacement: max_displacement)
}

/// min_duration sets the value of min_duration for this LongPressGesture.
///
pub fn min_duration(
  record: LongPressGesture,
  min_duration: Float,
) -> LongPressGesture {
  LongPressGesture(..record, min_duration: min_duration)
}

/// max_press_interval sets the value of max_press_interval for this LongPressGesture.
///
pub fn max_press_interval(
  record: LongPressGesture,
  max_press_interval: Float,
) -> LongPressGesture {
  LongPressGesture(..record, max_press_interval: max_press_interval)
}

// --- Renderers ---

/// render creates a Lustre Element for a LongPressGesture
///
pub fn render(
  model: LongPressGesture,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  element.element(
    "m3e-long-press-gesture",
    list.flatten([
      [
        attr.option(model.for, fn(_) { "for" }, function.identity, default_for),
        attr.with_default(
          "buttons",
          attr.list_to_spaced_string(
            model.buttons,
            gesture_input_button.to_string,
          ),
          attr.list_to_spaced_string(
            default_buttons,
            gesture_input_button.to_string,
          ),
        ),
        attr.with_default(
          "pointer-types",
          attr.list_to_spaced_string(
            model.pointer_types,
            pointer_type.to_string,
          ),
          attr.list_to_spaced_string(
            default_pointer_types,
            pointer_type.to_string,
          ),
        ),
        attr.boolean("disabled", model.disabled == IsDisabled),
        attr.with_default("priority", model.priority, default_priority),
        attr.with_default(
          "pointers",
          float.to_string(model.pointers),
          float.to_string(default_pointers),
        ),
        attr.with_default(
          "max-displacement",
          float.to_string(model.max_displacement),
          float.to_string(default_max_displacement),
        ),
        attr.with_default(
          "min-duration",
          float.to_string(model.min_duration),
          float.to_string(default_min_duration),
        ),
        attr.with_default(
          "max-press-interval",
          float.to_string(model.max_press_interval),
          float.to_string(default_max_press_interval),
        ),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    [],
  )
}

/// render_config creates a Lustre Element from a LongPressGesture Config
///
pub fn render_config(
  c: Config,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  render(from_config(c), attributes)
}
