//// MenuPositionY
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type MenuPositionY {
  Above
  Below
}

pub fn to_string(level: MenuPositionY) -> String {
  case level {
    Above -> "above"
    Below -> "below"
  }
}
