//// MenuTrigger is an element, nested within a clickable element, used to open a menu.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/function
import gleam/list
import gleam/option.{type Option, None}
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr

// --- Types ---

/// MenuTrigger is a View Model for this component
///
/// ## Fields:
///
/// - for: The identifier of the interactive control to which this element is attached.
///
pub opaque type MenuTrigger {
  MenuTrigger(for: Option(String))
}

// --- Defaults ---

pub const default_for: Option(String) = None

// --- Constructors ---

/// new creates a new MenuTrigger with the default configuration.
///
pub fn new(for: Option(String)) -> MenuTrigger {
  MenuTrigger(for: for)
}

// --- Setters ---

/// for sets the value of for for this MenuTrigger.
///
pub fn for(_: MenuTrigger, for: Option(String)) -> MenuTrigger {
  MenuTrigger(for: for)
}

// --- Renderers ---

/// render creates a Lustre Element for a MenuTrigger
///
pub fn render(
  model: MenuTrigger,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  element.element(
    "m3e-menu-trigger",
    list.flatten([
      [
        attr.option(model.for, fn(_) { "for" }, function.identity, default_for),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    children,
  )
}
