//// MenuPositionX
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type MenuPositionX {
  Before
  After
}

pub fn to_string(level: MenuPositionX) -> String {
  case level {
    Before -> "before"
    After -> "after"
  }
}
