//// MotionScheme
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type MotionScheme {
  Standard
  Expressive
}

pub fn to_string(level: MotionScheme) -> String {
  case level {
    Standard -> "standard"
    Expressive -> "expressive"
  }
}
