//// NavItemOrientation
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type NavItemOrientation {
  Vertical
  Horizontal
}

pub fn to_string(level: NavItemOrientation) -> String {
  case level {
    Vertical -> "vertical"
    Horizontal -> "horizontal"
  }
}
