//// NavBarMode
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type NavBarMode {
  Compact
  Expanded
  Auto
}

pub fn to_string(level: NavBarMode) -> String {
  case level {
    Compact -> "compact"
    Expanded -> "expanded"
    Auto -> "auto"
  }
}
