//// OptionPanelState
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type OptionPanelState {
  Loading
  NoData
  Content
}

pub fn to_string(level: OptionPanelState) -> String {
  case level {
    Loading -> "loading"
    NoData -> "no-data"
    Content -> "content"
  }
}
