//// Option is an option that can be selected.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/list
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr
import m3e/text_highlight_mode.{type TextHighlightMode}

// --- Types ---

/// Option is a View Model for this component
///
/// ## Fields:
///
/// - disabled: Whether the element is disabled.
/// - disable_highlight: Whether text highlighting is disabled.
/// - highlight_mode: The mode in which to highlight a term.
/// - selected: Whether the element is selected.
/// - term: The search term to highlight.
/// - value: A string representing the value of the option.
///
pub opaque type Option {
  Option(
    disabled: Disabled,
    disable_highlight: DisableHighlight,
    highlight_mode: TextHighlightMode,
    selected: Selected,
    term: String,
    value: String,
  )
}

/// Disabled is whether the element is disabled.
///
pub type Disabled {
  IsDisabled
  IsNotDisabled
}

/// DisableHighlight is whether text highlighting is disabled.
///
pub type DisableHighlight {
  IsDisableHighlight
  IsNotDisableHighlight
}

/// Selected is whether the element is selected.
///
pub type Selected {
  IsSelected
  IsNotSelected
}

// --- Defaults ---

pub const default_disabled: Disabled = IsNotDisabled

pub const default_disable_highlight: DisableHighlight = IsNotDisableHighlight

pub const default_highlight_mode: TextHighlightMode = text_highlight_mode.Contains

pub const default_selected: Selected = IsNotSelected

pub const default_term: String = ""

pub const default_value: String = ""

// --- Configuration ---

/// Config is a public record for configuring this component.
///
pub type Config {
  Config(
    disabled: Disabled,
    disable_highlight: DisableHighlight,
    highlight_mode: TextHighlightMode,
    selected: Selected,
    term: String,
    value: String,
  )
}

/// default_config is the default configuration for this component.
///
pub fn default_config() -> Config {
  Config(
    disabled: IsNotDisabled,
    disable_highlight: IsNotDisableHighlight,
    highlight_mode: text_highlight_mode.Contains,
    selected: IsNotSelected,
    term: "",
    value: "",
  )
}

// --- Constructors ---

/// from_config creates a new Option from the given configuration.
///
pub fn from_config(config: Config) -> Option {
  Option(
    disabled: config.disabled,
    disable_highlight: config.disable_highlight,
    highlight_mode: config.highlight_mode,
    selected: config.selected,
    term: config.term,
    value: config.value,
  )
}

/// new creates a new Option with the default configuration.
///
pub fn new() -> Option {
  from_config(default_config())
}

// --- Setters ---

/// disabled sets the value of disabled for this Option.
///
pub fn disabled(record: Option, disabled: Disabled) -> Option {
  Option(..record, disabled: disabled)
}

/// disable_highlight sets the value of disable_highlight for this Option.
///
pub fn disable_highlight(
  record: Option,
  disable_highlight: DisableHighlight,
) -> Option {
  Option(..record, disable_highlight: disable_highlight)
}

/// highlight_mode sets the value of highlight_mode for this Option.
///
pub fn highlight_mode(
  record: Option,
  highlight_mode: TextHighlightMode,
) -> Option {
  Option(..record, highlight_mode: highlight_mode)
}

/// selected sets the value of selected for this Option.
///
pub fn selected(record: Option, selected: Selected) -> Option {
  Option(..record, selected: selected)
}

/// term sets the value of term for this Option.
///
pub fn term(record: Option, term: String) -> Option {
  Option(..record, term: term)
}

/// value sets the value of value for this Option.
///
pub fn value(record: Option, value: String) -> Option {
  Option(..record, value: value)
}

// --- Renderers ---

/// render creates a Lustre Element for a Option
///
pub fn render(
  model: Option,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  element.element(
    "m3e-option",
    list.flatten([
      [
        attr.boolean("disabled", model.disabled == IsDisabled),
        attr.boolean(
          "disable-highlight",
          model.disable_highlight == IsDisableHighlight,
        ),
        attr.with_default(
          "highlight-mode",
          text_highlight_mode.to_string(model.highlight_mode),
          text_highlight_mode.to_string(default_highlight_mode),
        ),
        attr.boolean("selected", model.selected == IsSelected),
        attr.with_default("term", model.term, default_term),
        attr.with_default("value", model.value, default_value),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    children,
  )
}

/// render_config creates a Lustre Element from a Option Config
///
pub fn render_config(
  c: Config,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  render(from_config(c), attributes, children)
}
