//// PanGesture is a non-visual element used to detect a pan gesture for an associated element.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/float
import gleam/function
import gleam/list
import gleam/option.{type Option, None}
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr
import m3e/gesture_input_button.{type GestureInputButton}
import m3e/pan_gesture_activation_mode.{type PanGestureActivationMode}
import m3e/pan_gesture_lock_axis.{type PanGestureLockAxis}
import m3e/pointer_type.{type PointerType}

// --- Types ---

/// PanGesture is a View Model for this component
///
/// ## Fields:
///
/// - for: The identifier of the interactive control to which this element is attached.
/// - buttons: Which buttons can be pressed.
/// - pointer_types: Which types of pointers can be used to recognize gestures.
/// - disabled: Whether gesture recognition is disabled.
/// - priority: The priority in which to recognize gestures.
/// - activation_mode: Mode in which to activate the gesture.
/// - min_displacement: Minimum distance (px) a pointer can move before the gesture starts.
/// - lock_axis: Locks movement to an axis.
/// - axis_threshold: Minimum total displacement (px) required before axis locking resolves orientation.
/// - delta_threshold: Minimum incremental movement (px) on the secondary axis required before emitting move updates.
///
pub opaque type PanGesture {
  PanGesture(
    for: Option(String),
    buttons: List(GestureInputButton),
    pointer_types: List(PointerType),
    disabled: Disabled,
    priority: Float,
    activation_mode: PanGestureActivationMode,
    min_displacement: Float,
    lock_axis: PanGestureLockAxis,
    axis_threshold: Float,
    delta_threshold: Float,
  )
}

/// Disabled is whether gesture recognition is disabled.
///
pub type Disabled {
  IsDisabled
  IsNotDisabled
}

// --- Defaults ---

pub const default_for: Option(String) = None

pub const default_buttons: List(GestureInputButton) = [
  gesture_input_button.Primary,
]

pub const default_pointer_types: List(PointerType) = [
  pointer_type.Mouse,
  pointer_type.Pen,
  pointer_type.Touch,
]

pub const default_disabled: Disabled = IsNotDisabled

pub const default_priority: Float = 1.0

pub const default_activation_mode: PanGestureActivationMode = pan_gesture_activation_mode.Press

pub const default_min_displacement: Float = 4.0

pub const default_lock_axis: PanGestureLockAxis = pan_gesture_lock_axis.None

pub const default_axis_threshold: Float = 8.0

pub const default_delta_threshold: Float = 0.0

// --- Configuration ---

/// Config is a public record for configuring this component.
///
pub type Config {
  Config(
    for: Option(String),
    buttons: List(GestureInputButton),
    pointer_types: List(PointerType),
    disabled: Disabled,
    priority: Float,
    activation_mode: PanGestureActivationMode,
    min_displacement: Float,
    lock_axis: PanGestureLockAxis,
    axis_threshold: Float,
    delta_threshold: Float,
  )
}

/// default_config is the default configuration for this component.
///
pub fn default_config() -> Config {
  Config(
    for: None,
    buttons: [gesture_input_button.Primary],
    pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
    disabled: IsNotDisabled,
    priority: 1.0,
    activation_mode: pan_gesture_activation_mode.Press,
    min_displacement: 4.0,
    lock_axis: pan_gesture_lock_axis.None,
    axis_threshold: 8.0,
    delta_threshold: 0.0,
  )
}

// --- Constructors ---

/// from_config creates a new PanGesture from the given configuration.
///
pub fn from_config(config: Config) -> PanGesture {
  PanGesture(
    for: config.for,
    buttons: config.buttons,
    pointer_types: config.pointer_types,
    disabled: config.disabled,
    priority: config.priority,
    activation_mode: config.activation_mode,
    min_displacement: config.min_displacement,
    lock_axis: config.lock_axis,
    axis_threshold: config.axis_threshold,
    delta_threshold: config.delta_threshold,
  )
}

/// new creates a new PanGesture with the default configuration.
///
pub fn new() -> PanGesture {
  from_config(default_config())
}

// --- Setters ---

/// for sets the value of for for this PanGesture.
///
pub fn for(record: PanGesture, for: Option(String)) -> PanGesture {
  PanGesture(..record, for: for)
}

/// buttons sets the value of buttons for this PanGesture.
///
pub fn buttons(
  record: PanGesture,
  buttons: List(GestureInputButton),
) -> PanGesture {
  PanGesture(..record, buttons: buttons)
}

/// pointer_types sets the value of pointer_types for this PanGesture.
///
pub fn pointer_types(
  record: PanGesture,
  pointer_types: List(PointerType),
) -> PanGesture {
  PanGesture(..record, pointer_types: pointer_types)
}

/// disabled sets the value of disabled for this PanGesture.
///
pub fn disabled(record: PanGesture, disabled: Disabled) -> PanGesture {
  PanGesture(..record, disabled: disabled)
}

/// priority sets the value of priority for this PanGesture.
///
pub fn priority(record: PanGesture, priority: Float) -> PanGesture {
  PanGesture(..record, priority: priority)
}

/// activation_mode sets the value of activation_mode for this PanGesture.
///
pub fn activation_mode(
  record: PanGesture,
  activation_mode: PanGestureActivationMode,
) -> PanGesture {
  PanGesture(..record, activation_mode: activation_mode)
}

/// min_displacement sets the value of min_displacement for this PanGesture.
///
pub fn min_displacement(
  record: PanGesture,
  min_displacement: Float,
) -> PanGesture {
  PanGesture(..record, min_displacement: min_displacement)
}

/// lock_axis sets the value of lock_axis for this PanGesture.
///
pub fn lock_axis(
  record: PanGesture,
  lock_axis: PanGestureLockAxis,
) -> PanGesture {
  PanGesture(..record, lock_axis: lock_axis)
}

/// axis_threshold sets the value of axis_threshold for this PanGesture.
///
pub fn axis_threshold(record: PanGesture, axis_threshold: Float) -> PanGesture {
  PanGesture(..record, axis_threshold: axis_threshold)
}

/// delta_threshold sets the value of delta_threshold for this PanGesture.
///
pub fn delta_threshold(
  record: PanGesture,
  delta_threshold: Float,
) -> PanGesture {
  PanGesture(..record, delta_threshold: delta_threshold)
}

// --- Renderers ---

/// render creates a Lustre Element for a PanGesture
///
pub fn render(
  model: PanGesture,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  element.element(
    "m3e-pan-gesture",
    list.flatten([
      [
        attr.option(model.for, fn(_) { "for" }, function.identity, default_for),
        attr.with_default(
          "buttons",
          attr.list_to_spaced_string(
            model.buttons,
            gesture_input_button.to_string,
          ),
          attr.list_to_spaced_string(
            default_buttons,
            gesture_input_button.to_string,
          ),
        ),
        attr.with_default(
          "pointer-types",
          attr.list_to_spaced_string(
            model.pointer_types,
            pointer_type.to_string,
          ),
          attr.list_to_spaced_string(
            default_pointer_types,
            pointer_type.to_string,
          ),
        ),
        attr.boolean("disabled", model.disabled == IsDisabled),
        attr.with_default(
          "priority",
          float.to_string(model.priority),
          float.to_string(default_priority),
        ),
        attr.with_default(
          "activation-mode",
          pan_gesture_activation_mode.to_string(model.activation_mode),
          pan_gesture_activation_mode.to_string(default_activation_mode),
        ),
        attr.with_default(
          "min-displacement",
          float.to_string(model.min_displacement),
          float.to_string(default_min_displacement),
        ),
        attr.with_default(
          "lock-axis",
          pan_gesture_lock_axis.to_string(model.lock_axis),
          pan_gesture_lock_axis.to_string(default_lock_axis),
        ),
        attr.with_default(
          "axis-threshold",
          float.to_string(model.axis_threshold),
          float.to_string(default_axis_threshold),
        ),
        attr.with_default(
          "delta-threshold",
          float.to_string(model.delta_threshold),
          float.to_string(default_delta_threshold),
        ),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    [],
  )
}

/// render_config creates a Lustre Element from a PanGesture Config
///
pub fn render_config(
  c: Config,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  render(from_config(c), attributes)
}
