//// PanGestureLockAxis
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type PanGestureLockAxis {
  X
  Y
  Auto
  None
}

pub fn to_string(level: PanGestureLockAxis) -> String {
  case level {
    X -> "x"
    Y -> "y"
    Auto -> "auto"
    None -> "none"
  }
}
