//// PanGestureOrientation
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type PanGestureOrientation {
  Horizontal
  Vertical
}

pub fn to_string(level: PanGestureOrientation) -> String {
  case level {
    Horizontal -> "horizontal"
    Vertical -> "vertical"
  }
}
