//// RepeatGesture is a non-visual element used to detect a repeated gesture for an associated element.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/float
import gleam/function
import gleam/list
import gleam/option.{type Option, None}
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr
import m3e/gesture_input_button.{type GestureInputButton}

// --- Types ---

/// RepeatGesture is a View Model for this component
///
/// ## Fields:
///
/// - allowed_buttons: Which buttons can be pressed.
/// - disabled: Whether gesture recognition is disabled.
/// - priority: The priority in which to recognize gestures.
/// - max_interval: Maximum time (ms) between gestures before the repeated gesture fails.
/// - count: Number of times a gesture must be repeated.
/// - for: The identifier of the interactive control to which this element is attached.
///
pub opaque type RepeatGesture {
  RepeatGesture(
    allowed_buttons: GestureInputButton,
    disabled: Disabled,
    priority: Float,
    max_interval: Float,
    count: Float,
    for: Option(String),
  )
}

/// Disabled is whether gesture recognition is disabled.
///
pub type Disabled {
  IsDisabled
  IsNotDisabled
}

// --- Defaults ---

pub const default_allowed_buttons: GestureInputButton = gesture_input_button.Primary

pub const default_disabled: Disabled = IsNotDisabled

pub const default_priority: Float = 1.0

pub const default_max_interval: Float = 250.0

pub const default_count: Float = 2.0

pub const default_for: Option(String) = None

// --- Configuration ---

/// Config is a public record for configuring this component.
///
pub type Config {
  Config(
    allowed_buttons: GestureInputButton,
    disabled: Disabled,
    priority: Float,
    max_interval: Float,
    count: Float,
    for: Option(String),
  )
}

/// default_config is the default configuration for this component.
///
pub fn default_config() -> Config {
  Config(
    allowed_buttons: gesture_input_button.Primary,
    disabled: IsNotDisabled,
    priority: 1.0,
    max_interval: 250.0,
    count: 2.0,
    for: None,
  )
}

// --- Constructors ---

/// from_config creates a new RepeatGesture from the given configuration.
///
pub fn from_config(config: Config) -> RepeatGesture {
  RepeatGesture(
    allowed_buttons: config.allowed_buttons,
    disabled: config.disabled,
    priority: config.priority,
    max_interval: config.max_interval,
    count: config.count,
    for: config.for,
  )
}

/// new creates a new RepeatGesture with the default configuration.
///
pub fn new() -> RepeatGesture {
  from_config(default_config())
}

// --- Setters ---

/// allowed_buttons sets the value of allowed_buttons for this RepeatGesture.
///
pub fn allowed_buttons(
  record: RepeatGesture,
  allowed_buttons: GestureInputButton,
) -> RepeatGesture {
  RepeatGesture(..record, allowed_buttons: allowed_buttons)
}

/// disabled sets the value of disabled for this RepeatGesture.
///
pub fn disabled(record: RepeatGesture, disabled: Disabled) -> RepeatGesture {
  RepeatGesture(..record, disabled: disabled)
}

/// priority sets the value of priority for this RepeatGesture.
///
pub fn priority(record: RepeatGesture, priority: Float) -> RepeatGesture {
  RepeatGesture(..record, priority: priority)
}

/// max_interval sets the value of max_interval for this RepeatGesture.
///
pub fn max_interval(
  record: RepeatGesture,
  max_interval: Float,
) -> RepeatGesture {
  RepeatGesture(..record, max_interval: max_interval)
}

/// count sets the value of count for this RepeatGesture.
///
pub fn count(record: RepeatGesture, count: Float) -> RepeatGesture {
  RepeatGesture(..record, count: count)
}

/// for sets the value of for for this RepeatGesture.
///
pub fn for(record: RepeatGesture, for: Option(String)) -> RepeatGesture {
  RepeatGesture(..record, for: for)
}

// --- Renderers ---

/// render creates a Lustre Element for a RepeatGesture
///
pub fn render(
  model: RepeatGesture,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  element.element(
    "m3e-repeat-gesture",
    list.flatten([
      [
        attr.with_default(
          "allowed-buttons",
          gesture_input_button.to_string(model.allowed_buttons),
          gesture_input_button.to_string(default_allowed_buttons),
        ),
        attr.boolean("disabled", model.disabled == IsDisabled),
        attr.with_default(
          "priority",
          float.to_string(model.priority),
          float.to_string(default_priority),
        ),
        attr.with_default(
          "max-interval",
          float.to_string(model.max_interval),
          float.to_string(default_max_interval),
        ),
        attr.with_default(
          "count",
          float.to_string(model.count),
          float.to_string(default_count),
        ),
        attr.option(model.for, fn(_) { "for" }, function.identity, default_for),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    [],
  )
}

/// render_config creates a Lustre Element from a RepeatGesture Config
///
pub fn render_config(
  c: Config,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  render(from_config(c), attributes)
}
