//// RichTooltipPosition
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type RichTooltipPosition {
  AboveAfter
  AboveBefore
  BelowBefore
  BelowAfter
  Before
  After
  Above
  Below
}

pub fn to_string(level: RichTooltipPosition) -> String {
  case level {
    AboveAfter -> "above-after"
    AboveBefore -> "above-before"
    BelowBefore -> "below-before"
    BelowAfter -> "below-after"
    Before -> "before"
    After -> "after"
    Above -> "above"
    Below -> "below"
  }
}
