//// SearchViewMode
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type SearchViewMode {
  Fullscreen
  Docked
  Auto
}

pub fn to_string(level: SearchViewMode) -> String {
  case level {
    Fullscreen -> "fullscreen"
    Docked -> "docked"
    Auto -> "auto"
  }
}
