//// SequenceGesture is a non-visual element used to detect a sequence of gestures for an associated element.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/float
import gleam/function
import gleam/list
import gleam/option.{type Option, None}
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr
import m3e/gesture_input_button.{type GestureInputButton}
import m3e/pointer_type.{type PointerType}

// --- Types ---

/// SequenceGesture is a View Model for this component
///
/// ## Fields:
///
/// - for: The identifier of the interactive control to which this element is attached.
/// - buttons: Which buttons can be pressed.
/// - pointer_types: Which types of pointers can be used to recognize gestures.
/// - disabled: Whether gesture recognition is disabled.
/// - priority: The priority in which to recognize gestures.
/// - max_interval: Maximum time (ms) between gestures before the sequence fails.
///
pub opaque type SequenceGesture {
  SequenceGesture(
    for: Option(String),
    buttons: List(GestureInputButton),
    pointer_types: List(PointerType),
    disabled: Disabled,
    priority: Float,
    max_interval: Float,
  )
}

/// Disabled is whether gesture recognition is disabled.
///
pub type Disabled {
  IsDisabled
  IsNotDisabled
}

// --- Defaults ---

pub const default_for: Option(String) = None

pub const default_buttons: List(GestureInputButton) = [
  gesture_input_button.Primary,
]

pub const default_pointer_types: List(PointerType) = [
  pointer_type.Mouse,
  pointer_type.Pen,
  pointer_type.Touch,
]

pub const default_disabled: Disabled = IsNotDisabled

pub const default_priority: Float = 1.0

pub const default_max_interval: Float = 250.0

// --- Configuration ---

/// Config is a public record for configuring this component.
///
pub type Config {
  Config(
    for: Option(String),
    buttons: List(GestureInputButton),
    pointer_types: List(PointerType),
    disabled: Disabled,
    priority: Float,
    max_interval: Float,
  )
}

/// default_config is the default configuration for this component.
///
pub fn default_config() -> Config {
  Config(
    for: None,
    buttons: [gesture_input_button.Primary],
    pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
    disabled: IsNotDisabled,
    priority: 1.0,
    max_interval: 250.0,
  )
}

// --- Constructors ---

/// from_config creates a new SequenceGesture from the given configuration.
///
pub fn from_config(config: Config) -> SequenceGesture {
  SequenceGesture(
    for: config.for,
    buttons: config.buttons,
    pointer_types: config.pointer_types,
    disabled: config.disabled,
    priority: config.priority,
    max_interval: config.max_interval,
  )
}

/// new creates a new SequenceGesture with the default configuration.
///
pub fn new() -> SequenceGesture {
  from_config(default_config())
}

// --- Setters ---

/// for sets the value of for for this SequenceGesture.
///
pub fn for(record: SequenceGesture, for: Option(String)) -> SequenceGesture {
  SequenceGesture(..record, for: for)
}

/// buttons sets the value of buttons for this SequenceGesture.
///
pub fn buttons(
  record: SequenceGesture,
  buttons: List(GestureInputButton),
) -> SequenceGesture {
  SequenceGesture(..record, buttons: buttons)
}

/// pointer_types sets the value of pointer_types for this SequenceGesture.
///
pub fn pointer_types(
  record: SequenceGesture,
  pointer_types: List(PointerType),
) -> SequenceGesture {
  SequenceGesture(..record, pointer_types: pointer_types)
}

/// disabled sets the value of disabled for this SequenceGesture.
///
pub fn disabled(
  record: SequenceGesture,
  disabled: Disabled,
) -> SequenceGesture {
  SequenceGesture(..record, disabled: disabled)
}

/// priority sets the value of priority for this SequenceGesture.
///
pub fn priority(record: SequenceGesture, priority: Float) -> SequenceGesture {
  SequenceGesture(..record, priority: priority)
}

/// max_interval sets the value of max_interval for this SequenceGesture.
///
pub fn max_interval(
  record: SequenceGesture,
  max_interval: Float,
) -> SequenceGesture {
  SequenceGesture(..record, max_interval: max_interval)
}

// --- Renderers ---

/// render creates a Lustre Element for a SequenceGesture
///
pub fn render(
  model: SequenceGesture,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  element.element(
    "m3e-sequence-gesture",
    list.flatten([
      [
        attr.option(model.for, fn(_) { "for" }, function.identity, default_for),
        attr.with_default(
          "buttons",
          attr.list_to_spaced_string(
            model.buttons,
            gesture_input_button.to_string,
          ),
          attr.list_to_spaced_string(
            default_buttons,
            gesture_input_button.to_string,
          ),
        ),
        attr.with_default(
          "pointer-types",
          attr.list_to_spaced_string(
            model.pointer_types,
            pointer_type.to_string,
          ),
          attr.list_to_spaced_string(
            default_pointer_types,
            pointer_type.to_string,
          ),
        ),
        attr.boolean("disabled", model.disabled == IsDisabled),
        attr.with_default(
          "priority",
          float.to_string(model.priority),
          float.to_string(default_priority),
        ),
        attr.with_default(
          "max-interval",
          float.to_string(model.max_interval),
          float.to_string(default_max_interval),
        ),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    children,
  )
}

/// render_config creates a Lustre Element from a SequenceGesture Config
///
pub fn render_config(
  c: Config,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  render(from_config(c), attributes, children)
}
