//// SkeletonAnimation
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type SkeletonAnimation {
  Pulse
  Wave
  None
}

pub fn to_string(level: SkeletonAnimation) -> String {
  case level {
    Pulse -> "pulse"
    Wave -> "wave"
    None -> "none"
  }
}
