//// SkeletonShape
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type SkeletonShape {
  Circular
  Rounded
  Square
  Auto
}

pub fn to_string(level: SkeletonShape) -> String {
  case level {
    Circular -> "circular"
    Rounded -> "rounded"
    Square -> "square"
    Auto -> "auto"
  }
}
