//// SliderSize
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type SliderSize {
  ExtraSmall
  Small
  Medium
  Large
  ExtraLarge
}

pub fn to_string(level: SliderSize) -> String {
  case level {
    ExtraSmall -> "extra-small"
    Small -> "small"
    Medium -> "medium"
    Large -> "large"
    ExtraLarge -> "extra-large"
  }
}
