//// SplitPaneOrientation
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type SplitPaneOrientation {
  Horizontal
  Vertical
  Auto
}

pub fn to_string(level: SplitPaneOrientation) -> String {
  case level {
    Horizontal -> "horizontal"
    Vertical -> "vertical"
    Auto -> "auto"
  }
}
