//// SwipeGesture is a non-visual element used to detect a swipe gesture for an associated element.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/float
import gleam/function
import gleam/list
import gleam/option.{type Option, None}
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr
import m3e/gesture_input_button.{type GestureInputButton}
import m3e/pointer_type.{type PointerType}
import m3e/swipe_gesture_direction.{type SwipeGestureDirection}

// --- Types ---

/// SwipeGesture is a View Model for this component
///
/// ## Fields:
///
/// - for: The identifier of the interactive control to which this element is attached.
/// - buttons: Which buttons can be pressed.
/// - pointer_types: Which types of pointers can be used to recognize gestures.
/// - disabled: Whether gesture recognition is disabled.
/// - priority: The priority in which to recognize gestures.
/// - max_displacement: * Maximum distance (px) a pointer can move before the gesture fails.
/// - min_velocity: Minimum velocity (px/ms) required before the gesture fails.
/// - direction_threshold: Minimum displacement (px) required before direction is considered valid.
/// - directions: The allowed directions of the swipe.
///
pub opaque type SwipeGesture {
  SwipeGesture(
    for: Option(String),
    buttons: List(GestureInputButton),
    pointer_types: List(PointerType),
    disabled: Disabled,
    priority: Float,
    max_displacement: Float,
    min_velocity: Float,
    direction_threshold: Float,
    directions: List(SwipeGestureDirection),
  )
}

/// Disabled is whether gesture recognition is disabled.
///
pub type Disabled {
  IsDisabled
  IsNotDisabled
}

// --- Defaults ---

pub const default_for: Option(String) = None

pub const default_buttons: List(GestureInputButton) = [
  gesture_input_button.Primary,
]

pub const default_pointer_types: List(PointerType) = [
  pointer_type.Mouse,
  pointer_type.Pen,
  pointer_type.Touch,
]

pub const default_disabled: Disabled = IsNotDisabled

pub const default_priority: Float = 1.0

pub const default_max_displacement: Float = 24.0

pub const default_min_velocity: Float = 0.3

pub const default_direction_threshold: Float = 8.0

pub const default_directions: List(SwipeGestureDirection) = [
  swipe_gesture_direction.Left,
  swipe_gesture_direction.Right,
  swipe_gesture_direction.Up,
  swipe_gesture_direction.Down,
]

// --- Configuration ---

/// Config is a public record for configuring this component.
///
pub type Config {
  Config(
    for: Option(String),
    buttons: List(GestureInputButton),
    pointer_types: List(PointerType),
    disabled: Disabled,
    priority: Float,
    max_displacement: Float,
    min_velocity: Float,
    direction_threshold: Float,
    directions: List(SwipeGestureDirection),
  )
}

/// default_config is the default configuration for this component.
///
pub fn default_config() -> Config {
  Config(
    for: None,
    buttons: [gesture_input_button.Primary],
    pointer_types: [pointer_type.Mouse, pointer_type.Pen, pointer_type.Touch],
    disabled: IsNotDisabled,
    priority: 1.0,
    max_displacement: 24.0,
    min_velocity: 0.3,
    direction_threshold: 8.0,
    directions: [
      swipe_gesture_direction.Left,
      swipe_gesture_direction.Right,
      swipe_gesture_direction.Up,
      swipe_gesture_direction.Down,
    ],
  )
}

// --- Constructors ---

/// from_config creates a new SwipeGesture from the given configuration.
///
pub fn from_config(config: Config) -> SwipeGesture {
  SwipeGesture(
    for: config.for,
    buttons: config.buttons,
    pointer_types: config.pointer_types,
    disabled: config.disabled,
    priority: config.priority,
    max_displacement: config.max_displacement,
    min_velocity: config.min_velocity,
    direction_threshold: config.direction_threshold,
    directions: config.directions,
  )
}

/// new creates a new SwipeGesture with the default configuration.
///
pub fn new() -> SwipeGesture {
  from_config(default_config())
}

// --- Setters ---

/// for sets the value of for for this SwipeGesture.
///
pub fn for(record: SwipeGesture, for: Option(String)) -> SwipeGesture {
  SwipeGesture(..record, for: for)
}

/// buttons sets the value of buttons for this SwipeGesture.
///
pub fn buttons(
  record: SwipeGesture,
  buttons: List(GestureInputButton),
) -> SwipeGesture {
  SwipeGesture(..record, buttons: buttons)
}

/// pointer_types sets the value of pointer_types for this SwipeGesture.
///
pub fn pointer_types(
  record: SwipeGesture,
  pointer_types: List(PointerType),
) -> SwipeGesture {
  SwipeGesture(..record, pointer_types: pointer_types)
}

/// disabled sets the value of disabled for this SwipeGesture.
///
pub fn disabled(record: SwipeGesture, disabled: Disabled) -> SwipeGesture {
  SwipeGesture(..record, disabled: disabled)
}

/// priority sets the value of priority for this SwipeGesture.
///
pub fn priority(record: SwipeGesture, priority: Float) -> SwipeGesture {
  SwipeGesture(..record, priority: priority)
}

/// max_displacement sets the value of max_displacement for this SwipeGesture.
///
pub fn max_displacement(
  record: SwipeGesture,
  max_displacement: Float,
) -> SwipeGesture {
  SwipeGesture(..record, max_displacement: max_displacement)
}

/// min_velocity sets the value of min_velocity for this SwipeGesture.
///
pub fn min_velocity(record: SwipeGesture, min_velocity: Float) -> SwipeGesture {
  SwipeGesture(..record, min_velocity: min_velocity)
}

/// direction_threshold sets the value of direction_threshold for this SwipeGesture.
///
pub fn direction_threshold(
  record: SwipeGesture,
  direction_threshold: Float,
) -> SwipeGesture {
  SwipeGesture(..record, direction_threshold: direction_threshold)
}

/// directions sets the value of directions for this SwipeGesture.
///
pub fn directions(
  record: SwipeGesture,
  directions: List(SwipeGestureDirection),
) -> SwipeGesture {
  SwipeGesture(..record, directions: directions)
}

// --- Renderers ---

/// render creates a Lustre Element for a SwipeGesture
///
pub fn render(
  model: SwipeGesture,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  element.element(
    "m3e-swipe-gesture",
    list.flatten([
      [
        attr.option(model.for, fn(_) { "for" }, function.identity, default_for),
        attr.with_default(
          "buttons",
          attr.list_to_spaced_string(
            model.buttons,
            gesture_input_button.to_string,
          ),
          attr.list_to_spaced_string(
            default_buttons,
            gesture_input_button.to_string,
          ),
        ),
        attr.with_default(
          "pointer-types",
          attr.list_to_spaced_string(
            model.pointer_types,
            pointer_type.to_string,
          ),
          attr.list_to_spaced_string(
            default_pointer_types,
            pointer_type.to_string,
          ),
        ),
        attr.boolean("disabled", model.disabled == IsDisabled),
        attr.with_default(
          "priority",
          float.to_string(model.priority),
          float.to_string(default_priority),
        ),
        attr.with_default(
          "max-displacement",
          float.to_string(model.max_displacement),
          float.to_string(default_max_displacement),
        ),
        attr.with_default(
          "min-velocity",
          float.to_string(model.min_velocity),
          float.to_string(default_min_velocity),
        ),
        attr.with_default(
          "direction-threshold",
          float.to_string(model.direction_threshold),
          float.to_string(default_direction_threshold),
        ),
        attr.with_default(
          "directions",
          attr.list_to_spaced_string(
            model.directions,
            swipe_gesture_direction.to_string,
          ),
          attr.list_to_spaced_string(
            default_directions,
            swipe_gesture_direction.to_string,
          ),
        ),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    [],
  )
}

/// render_config creates a Lustre Element from a SwipeGesture Config
///
pub fn render_config(
  c: Config,
  attributes: List(Attribute(msg)),
) -> Element(msg) {
  render(from_config(c), attributes)
}
