//// SwipeGestureDirection
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type SwipeGestureDirection {
  Left
  Right
  Up
  Down
}

pub fn to_string(level: SwipeGestureDirection) -> String {
  case level {
    Left -> "left"
    Right -> "right"
    Up -> "up"
    Down -> "down"
  }
}
