//// SwitchIcons
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type SwitchIcons {
  None
  Selected
  Both
}

pub fn to_string(level: SwitchIcons) -> String {
  case level {
    None -> "none"
    Selected -> "selected"
    Both -> "both"
  }
}
