//// Tab is an interactive element that, when activated, presents an associated tab panel.
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

import gleam/function
import gleam/list
import gleam/option.{type Option, None}
import lustre/attribute.{type Attribute}
import lustre/element.{type Element}
import m3e/attr

// --- Types ---

/// Tab is a View Model for this component
///
/// ## Fields:
///
/// - disabled: Whether the element is disabled.
/// - for: The identifier of the interactive control to which this element is attached.
/// - selected: Whether the element is selected.
///
pub opaque type Tab {
  Tab(disabled: Disabled, for: Option(String), selected: Selected)
}

/// Disabled is whether the element is disabled.
///
pub type Disabled {
  IsDisabled
  IsNotDisabled
}

/// Selected is whether the element is selected.
///
pub type Selected {
  IsSelected
  IsNotSelected
}

// --- Defaults ---

pub const default_disabled: Disabled = IsNotDisabled

pub const default_for: Option(String) = None

pub const default_selected: Selected = IsNotSelected

/// Slots are used in child elements to insert content into this component
///
pub type Slot {
  Icon
  // Renders an icon before the tab's label.
}

// --- Configuration ---

/// Config is a public record for configuring this component.
///
pub type Config {
  Config(disabled: Disabled, for: Option(String), selected: Selected)
}

/// default_config is the default configuration for this component.
///
pub fn default_config() -> Config {
  Config(disabled: IsNotDisabled, for: None, selected: IsNotSelected)
}

// --- Constructors ---

/// from_config creates a new Tab from the given configuration.
///
pub fn from_config(config: Config) -> Tab {
  Tab(disabled: config.disabled, for: config.for, selected: config.selected)
}

/// new creates a new Tab with the default configuration.
///
pub fn new() -> Tab {
  from_config(default_config())
}

// --- Setters ---

/// disabled sets the value of disabled for this Tab.
///
pub fn disabled(record: Tab, disabled: Disabled) -> Tab {
  Tab(..record, disabled: disabled)
}

/// for sets the value of for for this Tab.
///
pub fn for(record: Tab, for: Option(String)) -> Tab {
  Tab(..record, for: for)
}

/// selected sets the value of selected for this Tab.
///
pub fn selected(record: Tab, selected: Selected) -> Tab {
  Tab(..record, selected: selected)
}

// --- Renderers ---

/// render creates a Lustre Element for a Tab
///
pub fn render(
  model: Tab,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  element.element(
    "m3e-tab",
    list.flatten([
      [
        attr.boolean("disabled", model.disabled == IsDisabled),
        attr.option(model.for, fn(_) { "for" }, function.identity, default_for),
        attr.boolean("selected", model.selected == IsSelected),
      ],
      attributes,
    ])
      |> list.filter(fn(a) { a != attribute.none() }),
    children,
  )
}

/// render_config creates a Lustre Element from a Tab Config
///
pub fn render_config(
  c: Config,
  attributes: List(Attribute(msg)),
  children: List(Element(msg)),
) -> Element(msg) {
  render(from_config(c), attributes, children)
}

/// slot returns a Lustre Attribute(msg) for the given slot name
///
pub fn slot(s: Slot) -> Attribute(msg) {
  case s {
    Icon -> attribute.attribute("slot", "icon")
  }
}
