//// TabVariant
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type TabVariant {
  Primary
  Secondary
}

pub fn to_string(level: TabVariant) -> String {
  case level {
    Primary -> "primary"
    Secondary -> "secondary"
  }
}
