//// TextHighlightMode
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type TextHighlightMode {
  Contains
  StartsWith
  EndsWith
}

pub fn to_string(level: TextHighlightMode) -> String {
  case level {
    Contains -> "contains"
    StartsWith -> "starts-with"
    EndsWith -> "ends-with"
  }
}
