//// ThemeVariant
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type ThemeVariant {
  Monochrome
  Neutral
  TonalSpot
  Vibrant
  Expressive
  Fidelity
  Content
  Rainbow
  FruitSalad
}

pub fn to_string(level: ThemeVariant) -> String {
  case level {
    Monochrome -> "monochrome"
    Neutral -> "neutral"
    TonalSpot -> "tonal-spot"
    Vibrant -> "vibrant"
    Expressive -> "expressive"
    Fidelity -> "fidelity"
    Content -> "content"
    Rainbow -> "rainbow"
    FruitSalad -> "fruit-salad"
  }
}
