//// TimepickerMode
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type TimepickerMode {
  Dial
  Input
}

pub fn to_string(level: TimepickerMode) -> String {
  case level {
    Dial -> "dial"
    Input -> "input"
  }
}
