//// TooltipPosition
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type TooltipPosition {
  Above
  Below
  Before
  After
}

pub fn to_string(level: TooltipPosition) -> String {
  case level {
    Above -> "above"
    Below -> "below"
    Before -> "before"
    After -> "after"
  }
}
