//// TooltipTouchGestures
////
//// This file was generated by m3e/generator
////
////          DO NOT EDIT
////

pub type TooltipTouchGestures {
  Auto
  On
  Off
}

pub fn to_string(level: TooltipTouchGestures) -> String {
  case level {
    Auto -> "auto"
    On -> "on"
    Off -> "off"
  }
}
