name = "showcase"
version = "1.0.0"
description = "Showcase of muster capabilities"
licences = ["MIT"]

target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.70.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
m3e = { path = "../" }
monks_of_style = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.5 and < 3.0.0"

[tool.lustre]
entry = "app"

[tools.lustre.bin]
bun = "/home/bruce/.bun/bin/bun"
